// ==========================================
// ISO 27001:2022 SOA 통제항목 데이터 (2025 v1.1)
// 총 170개 통제항목, ISO ↔ ISMS-P 매핑 포함
// ==========================================

export interface ISOControl {
  iso_id: string;
  domain: string;
  control_no: string;
  control_name: string;
  check_item: string;
  status: '적용' | '부분적용' | '해당없음' | '미확인';
  operation: string;
  evidence: string;
  policy: string;
  mapped_isms: { req_id: string; subject: string; category: string }[];
  mapping_confidence: 'direct' | 'partial' | 'none';
}

export interface ISMSGapItem {
  req_id: string;
  category: string;
  subject: string;
  detail: string;
  compliance_cycle: string;
}

export const isoControls: ISOControl[] = [
  {
    iso_id: '5.1.1',
    domain: '5. 조직 통제',
    control_no: '5.1',
    control_name: '정보보호를 위한 정책',
    check_item: '정보보호정책의 구체적 시행을 위하여 세부적인 지침,절차가 수립되어 있습니까? 또한, 상하위 문서간의 상호관계 및 적용범위가 적정합니까?',
    status: '적용',
    operation: 'ㅇ 당사는 정보보호 규정 및 세부 지침, 절차를 제정하여 운영하고 있으며, 최고 경영자의 승인을 받아 제정하고 있음 ㅇ 정보보호 규정 및 지침은 문서화되어 임직원에 공유하고 있음(Flex) ㅇ 연 1회 이상 정기적으로 검토하여 적합성, 적절성, 유효성을 확인하고 있음',
    evidence: '- 정보보호 규정 및 지침 결재 내역 - 정보보호 규정 지침 공지 내역',
    policy: '- SP01_정보보호규정_Ver 2.0   · 제1조(목적)   · 제3조(정책의 유지관리)',
    mapped_isms: [{"req_id": "2.1.1", "subject": "정책의 유지관리", "category": "정책, 조직, 자산 관리"}],
    mapping_confidence: 'direct'
  },
  {
    iso_id: '5.1.2',
    domain: '5. 조직 통제',
    control_no: '5.1',
    control_name: '정보보호를 위한 정책',
    check_item: '정보보호 정책/지침/절차가 최고경영자에 의해 승인되었습니까?',
    status: '적용',
    operation: 'ㅇ 정책 지침 절차는 최고 경영자에 승인하고 있음',
    evidence: '- 규정 지침 경영진 승인',
    policy: '',
    mapped_isms: [{"req_id": "2.1.1", "subject": "정책의 유지관리", "category": "정책, 조직, 자산 관리"}],
    mapping_confidence: 'direct'
  },
  {
    iso_id: '5.1.3',
    domain: '5. 조직 통제',
    control_no: '5.1',
    control_name: '정보보호를 위한 정책',
    check_item: '모든 정보보호 정책은 문서화 되어 있어야 하며 모든 임직원과 관련자들에게 이해하기 쉬운 형태로 배포하였습니까?',
    status: '적용',
    operation: 'ㅇ  모든 임직원에게 메일 공유 및 인사 관리 시스템 문서에등록 되어  있음',
    evidence: '',
    policy: '',
    mapped_isms: [{"req_id": "2.1.1", "subject": "정책의 유지관리", "category": "정책, 조직, 자산 관리"}],
    mapping_confidence: 'direct'
  },
  {
    iso_id: '5.1.4',
    domain: '5. 조직 통제',
    control_no: '5.1',
    control_name: '정보보호를 위한 정책',
    check_item: '정기적으로 정보보호정책 및 관련문서의 적합성, 적절성, 유효성을 검토하고 있습니까?',
    status: '적용',
    operation: 'ㅇ 정기 비정기 법 개정에 따른 정책 검토 수행',
    evidence: '',
    policy: '',
    mapped_isms: [{"req_id": "2.1.1", "subject": "정책의 유지관리", "category": "정책, 조직, 자산 관리"}],
    mapping_confidence: 'direct'
  },
  {
    iso_id: '5.1.5',
    domain: '5. 조직 통제',
    control_no: '5.1',
    control_name: '정보보호를 위한 정책',
    check_item: '중대한 변화가 발생할 경우 정보보호정책의 적합성, 적절성, 유효성을 추가로 검토하고 있습니까? - 중대한 보안사고 발생 - 새로운 위협 또는 취약성의 발생 - 정보보호환경에 대한 중대한 변화 등',
    status: '적용',
    operation: 'ㅇ 규정 지침에 따라 추가 검토 수행',
    evidence: '',
    policy: '',
    mapped_isms: [{"req_id": "2.1.1", "subject": "정책의 유지관리", "category": "정책, 조직, 자산 관리"}],
    mapping_confidence: 'direct'
  },
  {
    iso_id: '5.2.1',
    domain: '5. 조직 통제',
    control_no: '5.2',
    control_name: '정보보호 역할 및 책임',
    check_item: '정보보호최고책임자(CISO)는 최고경영자의 지정을 받았습니까?',
    status: '적용',
    operation: 'ㅇ 당사는 정보보호최고책임자(CISO)를 지정하고, 정보보호위원회 및 정보보안팀을 운영하고 있음 ㅇ 정보보호규정을 통해 정보보호 직무와 관련된 역할과 책임을 수립 및 운영하고 있음',
    evidence: '- CISO 인사발령 내역 - CISO 신고서',
    policy: '- SG02_정보보안조직지침_Ver 2.0   · 제4조(정보보호최고책임자)   · 제6조(정보보호 주관 부서)',
    mapped_isms: [{"req_id": "1.1.3", "subject": "조직 구성", "category": "관리체계 기반 마련"}],
    mapping_confidence: 'direct'
  },
  {
    iso_id: '5.2.2',
    domain: '5. 조직 통제',
    control_no: '5.2',
    control_name: '정보보호 역할 및 책임',
    check_item: '정보보호관리자는 정보보호에 관한 업무를 총괄관리하고 있습니까? -정보보호정책 수립 -정보보호 위원회의 구성 및 운영 -위험분석 및 관리 -보안사고 대응 및 복구 등',
    status: '적용',
    operation: 'ㅇ 정보보호 팀 관리자는 정보보호에 관한 업무를 총괄 관리하고 있음',
    evidence: '',
    policy: '',
    mapped_isms: [{"req_id": "1.1.3", "subject": "조직 구성", "category": "관리체계 기반 마련"}],
    mapping_confidence: 'direct'
  },
  {
    iso_id: '5.3.1',
    domain: '5. 조직 통제',
    control_no: '5.3',
    control_name: '직무 분리',
    check_item: '정보보호 조직의 구성 및 각 조직과 구성원에 대한 업무분장 및 역할을 정의한 규정이 있습니까?',
    status: '적용',
    operation: 'ㅇ 개발, 운영, 보안, 감사 직무를 분리 운영하고 있으며, 인적보안 지침 내 역할과 책임을 명시하고 있음',
    evidence: '- 정보보호 서약서',
    policy: '- SG03_인적보안지침_Ver 2.0   · 제7조(직무 분리)   · 제8조(직무 분리 점검)',
    mapped_isms: [{"req_id": "2.2.3", "subject": "보안 서약", "category": "인적 보안"}],
    mapping_confidence: 'direct'
  },
  {
    iso_id: '5.3.2',
    domain: '5. 조직 통제',
    control_no: '5.3',
    control_name: '직무 분리',
    check_item: '규정에 따라 정보보호 관리 활동을 계획, 관리하는 정보보호 조직 체계가 있으며, 관련있는 조직의 부서들의 대표자들에 의해 조정되고 있습니까?',
    status: '적용',
    operation: 'ㅇ 모인 회사 규모에 맞는 정보보호조직 체계가 구성되어 있음',
    evidence: '',
    policy: '',
    mapped_isms: [{"req_id": "2.2.3", "subject": "보안 서약", "category": "인적 보안"}],
    mapping_confidence: 'direct'
  },
  {
    iso_id: '5.4.1',
    domain: '5. 조직 통제',
    control_no: '5.4',
    control_name: '경영진 책임',
    check_item: '경영진은 모든 직원 및 계약직이 조직이 수립한 정책과 절차에 따라 정보보안을 수행하도록 요구하였습니까?',
    status: '적용',
    operation: 'ㅇ 당사는 전사 임직원에 정보보호 규정 및 지침은 문서화하여 공유하고 있음(Flex)',
    evidence: '- 정보보호 규정 지침 공지 내역 - 정보보호서약서',
    policy: '- SP01_정보보호규정_Ver 2.0   · 제5조(정보보호최고책임자)   · 제7조(정보보호위원회)',
    mapped_isms: [{"req_id": "2.2.1", "subject": "주요 직무자 지정 및 관리", "category": "인적 보안"}],
    mapping_confidence: 'direct'
  },
  {
    iso_id: '5.5.1',
    domain: '5. 조직 통제',
    control_no: '5.5',
    control_name: '관계 당국과의 연락',
    check_item: '중요 정보보호관리활동을 위하여 기관과의 유기적인 관계를 맺고 있습니까?',
    status: '적용',
    operation: 'ㅇ 한국 핀테크 산업협회 및 금융보안원 등 외부 보안 관련 단체와 정기적인 보고 및 교류를 진행하고 있음',
    evidence: '- 금융보안원 레그테크 가입 내역 - 핀테크 산업 협회 가입 내역',
    policy: '- SG02_정보보안조직지침_Ver 2.0   · 제9조(정보보호위원회 구성 및 운영)',
    mapped_isms: [{"req_id": "1.1.2", "subject": "최고책임자의 지정", "category": "관리체계 기반 마련"}],
    mapping_confidence: 'direct'
  },
  {
    iso_id: '5.6.1',
    domain: '5. 조직 통제',
    control_no: '5.6',
    control_name: '전문가 그룹과의 연락',
    check_item: '중요 정보보호관리활동에 도움을 받기 위하여 외부 전문가의 도움을 받고 있습니까? - 정보보호정책 수립 - 보안관제 - 보안사고 대응 등',
    status: '적용',
    operation: 'ㅇ 한국 핀테크 산업협회 및 금융보안원 등 외부 보안 관련 단체와 정기적인 보고 및 교류를 진행하고 있음',
    evidence: '- 금융보안원 레그테크 가입 내역 - 핀테크 산업 협회 가입 내역',
    policy: '- SG02_정보보안조직지침_Ver 2.0   · 제9조(정보보호위원회 구성 및 운영)',
    mapped_isms: [{"req_id": "1.4.1", "subject": "법적 요구사항 준수 검토", "category": "관리체계 점검 및 개선"}],
    mapping_confidence: 'direct'
  },
  {
    iso_id: '5.7.1',
    domain: '5. 조직 통제',
    control_no: '5.7',
    control_name: '위협 인텔리전스',
    check_item: '정보보호 위협 공격 정보에 대한 증거 기반 분석 절차가 존재하고, 분석 정보를 활용한 방어 전략을 문서화 및 명세화하고 있습니까? - 조직에 특화된 위협 인텔리전스 - 계획 수립, 위협데이터 수집, 처리, 분석, 배포, 피드백과 같은 라이프사이클 관리',
    status: '적용',
    operation: 'ㅇ 당사는 금융보안원, KISA 등에서 제공하는 보안 위협 정보를 수집하고 있으며, 보안관제 및 취약점 점검에 반영하고 있음',
    evidence: '- 보안 관제 보고서(싸이버원) - 요구사항 6.1 증적 동일(위험관리 계획서/결과서)',
    policy: '- SG11_정보보안점검지침_Ver 2.0   · 제10조(기반시설 보안 취약점 분석 및 평가)',
    mapped_isms: [{"req_id": "2.11.1", "subject": "사고 예방 및 대응체계 구축", "category": "사고 예방 및 대응"}],
    mapping_confidence: 'direct'
  },
  {
    iso_id: '5.8.2',
    domain: '5. 조직 통제',
    control_no: '5.7',
    control_name: '위협 인텔리전스',
    check_item: '신규시스템 도입 및 응용시스템 개발, 기존시스템의 개선시 업무요구사항에 보안통제요구사항을 포함하고 분석 및 명세화 하고 있습니까?',
    status: '적용',
    operation: 'ㅇ신규 시스템 보안성 검토 명세화 되어 있으며 보안성 검토 수행 함',
    evidence: '',
    policy: '',
    mapped_isms: [{"req_id": "2.11.1", "subject": "사고 예방 및 대응체계 구축", "category": "사고 예방 및 대응"}],
    mapping_confidence: 'direct'
  },
  {
    iso_id: '5.8.1',
    domain: '5. 조직 통제',
    control_no: '5.8',
    control_name: '프로젝트 관리에서의 정보보호',
    check_item: '프로젝트 시 중요 정보보호를 위하여 외부자에게 동일한 보안대책을 적용하고 있습니까?',
    status: '적용',
    operation: 'ㅇ 모든 프로젝트에 대한 보안 검토 수행에 대한 규정을 수립 및 운영하고 있음 ㅇ 현재 외부자를 포함한 프로젝트 없음',
    evidence: '- 요구사항 6.1 동일 증적(자산 분석 및 위험관리 방법)',
    policy: '- SG04_외부주문보안지침_Ver 2.0   · 제11조(수탁자 보안 관리) - SG19_IT투자 및 비용관리지침_Ver 1.0   · 제5조(타당성 검토)   · 제6조(품의 및 계약)',
    mapped_isms: [{"req_id": "1.1.4", "subject": "범위 설정", "category": "관리체계 기반 마련"}],
    mapping_confidence: 'direct'
  },
  {
    iso_id: '5.9.1',
    domain: '5. 조직 통제',
    control_no: '5.9',
    control_name: '정보 및 기타 관련 자산 목록',
    check_item: '정보자산에 대한 정기적인 조사활동을 통하여 모든 주요 정보자산의 사용 목적과 현황을 유지관리하고 있습니까?',
    status: '적용',
    operation: 'ㅇ 정보자산 관리대장을 통해 정보자산을 업데이트 하고 있음',
    evidence: '- 정보자산 관리대장',
    policy: '- SG12_자산분석 및 위험관리지침_Ver 2.0   · 제7조(자산 분석 및 위험관리 절차)   · 제8조(자산분석)',
    mapped_isms: [{"req_id": "2.1.3", "subject": "정보자산 관리", "category": "인적 보안"}],
    mapping_confidence: 'direct'
  },
  {
    iso_id: '5.9.2',
    domain: '5. 조직 통제',
    control_no: '5.9',
    control_name: '정보 및 기타 관련 자산 목록',
    check_item: '정보자산에 대한 정기적인 조사활동과 중요도평가를 수행하고 있습니까?',
    status: '적용',
    operation: 'ㅇ 매년 1회 이상 정기적인 정보자산 조사 및 중요도 평가 수행함',
    evidence: '',
    policy: '',
    mapped_isms: [{"req_id": "2.1.3", "subject": "정보자산 관리", "category": "인적 보안"}],
    mapping_confidence: 'direct'
  },
  {
    iso_id: '5.9.3',
    domain: '5. 조직 통제',
    control_no: '5.9',
    control_name: '정보 및 기타 관련 자산 목록',
    check_item: '정보자산에 대한 소유자, 관리자,사용자 등에 대해 그 책임소재를 명시하고 라벨링되어 있습니까?   - 정보자산에 대한 소유자, 관리자, 책임자 표시',
    status: '적용',
    operation: 'ㅇ 정보자산 소유자 및 라베링 수행함',
    evidence: '',
    policy: '',
    mapped_isms: [{"req_id": "2.1.3", "subject": "정보자산 관리", "category": "인적 보안"}],
    mapping_confidence: 'direct'
  },
  {
    iso_id: '5.10.1',
    domain: '5. 조직 통제',
    control_no: '5.10',
    control_name: '정보 및 기타의 허용 가능한 사용',
    check_item: '정보자산 별로 평가기준, 사용 목적을 규정하고 있으며 규정에 의거하여 관리번호를 부여하여 관리하고 있습니까?  - 정보자산 분류체계  - 자산 사용 범위',
    status: '적용',
    operation: 'ㅇ 정보자산 관리대장을 통해 자산별 분류, 사용 목적 등을 관리 및 운영하고 있음',
    evidence: '- 정보자산 관리대장',
    policy: '- SG12_자산분석 및 위험관리지침_Ver 2.0   · 제7조(자산 분석 및 위험관리 절차)   · 제8조(자산분석)',
    mapped_isms: [{"req_id": "2.1.3", "subject": "정보자산 관리", "category": "인적 보안"}],
    mapping_confidence: 'direct'
  },
  {
    iso_id: '5.10.2',
    domain: '5. 조직 통제',
    control_no: '5.10',
    control_name: '정보 및 기타의 허용 가능한 사용',
    check_item: '정보자산의 보안등급별 취급절차를 등급 및 표시기준에 따라 규정하고 있습니까?',
    status: '적용',
    operation: 'ㅇ 정보자산의 보안등급별 취급절차를 등급 및 표시기준에 따라 규정 있음',
    evidence: '',
    policy: '',
    mapped_isms: [{"req_id": "2.1.3", "subject": "정보자산 관리", "category": "인적 보안"}],
    mapping_confidence: 'direct'
  },
  {
    iso_id: '5.11.1',
    domain: '5. 조직 통제',
    control_no: '5.11',
    control_name: '자산 반환',
    check_item: '직원, 외부자의 고용, 계약, 협약의 종료와 함께 조직의 모든 자산을 반환하고 확인하고 있습니까?',
    status: '적용',
    operation: 'ㅇ 퇴사 시 비밀유지서약서 및 퇴직자 체크리스트를 통해 회사에 대한 자산 반납을 확인하고 있음',
    evidence: '- 정보자산 관리대장 - 퇴직자 체크리스트 및 비밀유지서약서',
    policy: '- SG03_인적보안지침_Ver 2.0   · 제6조(퇴직 및 직무변경 시 보안관리)',
    mapped_isms: [{"req_id": "2.1.3", "subject": "정보자산 관리", "category": "인적 보안"}],
    mapping_confidence: 'direct'
  },
  {
    iso_id: '5.12.1',
    domain: '5. 조직 통제',
    control_no: '5.12',
    control_name: '정보 등급 분류',
    check_item: '정보자산의 가치, 법적 요구사항, 조직에 대한 민감도와 위험도 등에 관하여 분류기준이 마련되어 있습니까?',
    status: '적용',
    operation: 'ㅇ 관련 지침을 통해 정보자산의 중요도를 평가하는 기준을 수립 및 운영하고 있음 ㅇ 정보자산의 기밀성, 무결성, 가용성을 고려하여 중요도를 결정하고 보안등급을 부여하고 있음',
    evidence: '- 요구사항 6.1 증적 동일(위험관리 계획서)',
    policy: '- SG12_자산분석 및 위험관리지침_Ver 2.0   · 제7조(자산 분석 및 위험관리 절차)   · 제8조(자산분석)',
    mapped_isms: [{"req_id": "2.1.3", "subject": "정보자산 관리", "category": "인적 보안"}],
    mapping_confidence: 'direct'
  },
  {
    iso_id: '5.13.1',
    domain: '5. 조직 통제',
    control_no: '5.13',
    control_name: '정보 표식',
    check_item: '정보자산의 보안등급 부여, 표식 절차는 규정을 준수하고 있습니까?',
    status: '적용',
    operation: 'ㅇ 관련 지침을 통해 정보자산의 각 중요도에 따른 취급절차를 수립하고 있으며, 이행하고 있음',
    evidence: '- 정보자산 관리대장 - 요구사항 6.1 증적 동일(위험관리 계획서)',
    policy: '- SG12_자산분석 및 위험관리지침_Ver 2.0   · 제7조(자산 분석 및 위험관리 절차)   · 제8조(자산분석)',
    mapped_isms: [],
    mapping_confidence: 'none'
  },
  {
    iso_id: '5.14.1',
    domain: '5. 조직 통제',
    control_no: '5.14',
    control_name: '정보 전송',
    check_item: '정보의 교환시 공식적인 교환 정책, 절차, 통제 등의 규정이 수립되어 있습니까?',
    status: '적용',
    operation: 'ㅇ 관련 지침 등으로 외부자와 정보 교환 시 절차 및 보호대책 등을 수립하고 있음',
    evidence: '',
    policy: '- SG04_외부주문보안지침_Ver 2.0   · 제17조(자료관리) - SG10_암호화지침_Ver 2.0   · 제9조(중요정보 송∙수신 시 암호화)',
    mapped_isms: [{"req_id": "2.4.4", "subject": "보호설비 운영", "category": "물리 보안"}],
    mapping_confidence: 'direct'
  },
  {
    iso_id: '5.14.2',
    domain: '5. 조직 통제',
    control_no: '5.14',
    control_name: '정보 전송',
    check_item: '정보 및 소프트웨어에 대한 교환시 합의서 작성 규정이 존재하고 있습니까? - 관리적 책임 - 교환 및 합의절차 - 전송의 기술적 기준 - 인증기준 - 데이터의 책임성',
    status: '적용',
    operation: '',
    evidence: '',
    policy: '',
    mapped_isms: [{"req_id": "2.4.4", "subject": "보호설비 운영", "category": "물리 보안"}],
    mapping_confidence: 'direct'
  },
  {
    iso_id: '5.14.3',
    domain: '5. 조직 통제',
    control_no: '5.14',
    control_name: '정보 전송',
    check_item: '전자우편 서비스에 대해 다음의 책임과 위험을 고려한 보안지침 및 대책을 수립하여 운영하고 있습니까? - 전자우편 서비스의 가용성 - 전자우편 내용의 무결성 및 기밀성',
    status: '적용',
    operation: '',
    evidence: '',
    policy: '',
    mapped_isms: [{"req_id": "2.4.4", "subject": "보호설비 운영", "category": "물리 보안"}],
    mapping_confidence: 'direct'
  },
  {
    iso_id: '5.15.1',
    domain: '5. 조직 통제',
    control_no: '5.15',
    control_name: '접근 통제',
    check_item: '정보시스템 및 네트워크의 접근통제 정책을 규정하여 문서화 하였습니까? (보안 관리 등급에 따른 통제방법 및 범위 등의 정의 여부 확인)',
    status: '적용',
    operation: 'ㅇ 관련 지침을 통해 접근통제에 대한 정책을 수립 및 운영하고 있음 ㅇ 정보시스템별 접근 통제에 대한 정책을 수립 및 운영하고 있음   - 서버, DBMS, 쿠버네티스: QueryPie   - 그 외 SaaS 등 서비스: Okta 인증   - 네트워크 및 단말기: Okta, NAC, MDM',
    evidence: '',
    policy: '- SG08_정보시스템보안지침_Ver 2.0   · 제14조(정보시스템 접근통제)   · 제15조(정보시스템 외부 접근)',
    mapped_isms: [{"req_id": "2.5.1", "subject": "사용자 계정 관리", "category": "인증 및 권한관리"}],
    mapping_confidence: 'direct'
  },
  {
    iso_id: '5.15.2',
    domain: '5. 조직 통제',
    control_no: '5.15',
    control_name: '접근 통제',
    check_item: '정보시스템에 대한 접근통제가 정의되어 있으며 그 접근통제 정책에 데이터, 응용프로그램, 주요 시스템, 네트워크에 대한 접근 통제가 포함되어 있습니까?',
    status: '적용',
    operation: '',
    evidence: '',
    policy: '',
    mapped_isms: [{"req_id": "2.5.1", "subject": "사용자 계정 관리", "category": "인증 및 권한관리"}],
    mapping_confidence: 'direct'
  },
  {
    iso_id: '5.15.3',
    domain: '5. 조직 통제',
    control_no: '5.15',
    control_name: '접근 통제',
    check_item: '접근통제 정책에 대한 주기적 검토에 대한 규정이 있습니까?  -접근 모니터링 실시 및 정책 일치성 점검 규정  -접근통제 정책의 적정성 검토 규정',
    status: '적용',
    operation: '',
    evidence: '',
    policy: '',
    mapped_isms: [{"req_id": "2.5.1", "subject": "사용자 계정 관리", "category": "인증 및 권한관리"}],
    mapping_confidence: 'direct'
  },
  {
    iso_id: '5.15.4',
    domain: '5. 조직 통제',
    control_no: '5.15',
    control_name: '접근 통제',
    check_item: '접근통제 정책에 접근통제 관련 모니터링을 실시하고 이를 분석하며 접근통제 정책과 모니터링의 일치성을 주기적으로 점검하도록 규정하고 있습니까?  -접근 모니터링 실시 여부  -접근통제 정책과 접근통제 모니터링의 일치성 검토 여부  -접근통제 정책의 적정성 주기적 점검 여부',
    status: '부분적용',
    operation: '',
    evidence: '',
    policy: '',
    mapped_isms: [{"req_id": "2.5.1", "subject": "사용자 계정 관리", "category": "인증 및 권한관리"}],
    mapping_confidence: 'partial'
  },
  {
    iso_id: '5.15.5',
    domain: '5. 조직 통제',
    control_no: '5.15',
    control_name: '접근 통제',
    check_item: 'IP Address 체계적인 관리를 위한 규정이 정의되어 있으며 주기적으로 점검 하고 있습니까?',
    status: '적용',
    operation: '',
    evidence: '',
    policy: '',
    mapped_isms: [{"req_id": "2.5.1", "subject": "사용자 계정 관리", "category": "인증 및 권한관리"}],
    mapping_confidence: 'direct'
  },
  {
    iso_id: '5.15.6',
    domain: '5. 조직 통제',
    control_no: '5.15',
    control_name: '접근 통제',
    check_item: '보안유지를 위한 네트워크 보안정책 및 운영지침이 마련되어 있습니까? - Network Resource 접근권한 통제 - 원격 접속 설비 관리/ 원격 접속 인증 - 네트워크 분리 (IP주소 할당) - 네트워크 모니터링 수행 - 네트워크 변경관리 절차',
    status: '부분적용',
    operation: '',
    evidence: '',
    policy: '',
    mapped_isms: [{"req_id": "2.5.1", "subject": "사용자 계정 관리", "category": "인증 및 권한관리"}],
    mapping_confidence: 'partial'
  },
  {
    iso_id: '5.16.1',
    domain: '5. 조직 통제',
    control_no: '5.16',
    control_name: '계정 관리',
    check_item: '사용자 등록 및 해지 절차 (사용자 변경절차)가 있습니까?  -사용자 접근 등급체계  -직급 또는 직무별 사용자 계정 생성 및 권한부여',
    status: '적용',
    operation: 'ㅇ OKTA를 통해 연동된 시스템의 경우 사용자가 포함된 그룹별로 권한이 정의 및 부여되고 있음(소속팀 + 직무별로 구분) ㅇ 특수 계정의 경우 Slack을 통해 사용자 계정 신청을 받고 있음',
    evidence: '- 사용자 계정 생성 및 권한 부여 신청서(Slack) - 서버 접근통제 구현 화면(쿼리파이) - Okta 계정 목록',
    policy: '- SG05_계정관리지침_Ver 2.0   · 제3장 사용자 계정 관리',
    mapped_isms: [{"req_id": "2.5.2", "subject": "사용자 식별", "category": "인증 및 권한관리"}],
    mapping_confidence: 'direct'
  },
  {
    iso_id: '5.17.1',
    domain: '5. 조직 통제',
    control_no: '5.17',
    control_name: '인증 정보',
    check_item: '인증정보 할당 및 사용을 관리하기 위한 지침이 수립되어 있습니까?',
    status: '적용',
    operation: 'ㅇ 관련 지침을 통해 각 정보시스템의 인증정보 관리를 위한 절차 등을 수립하고 있음 ㅇ 각 시스템별로 비밀번호 정책을 수립 및 운영하고 있음(Okta: 3가지조합 8자리 이상/2차 인증)',
    evidence: '',
    policy: '- SG05_계정관리지침_Ver 2.0   · 제9조(비밀번호 관리) - SG10_암호화지침_Ver 2.0   · 제11조(암호화키 관리)',
    mapped_isms: [{"req_id": "2.5.2", "subject": "사용자 식별", "category": "인증 및 권한관리"}],
    mapping_confidence: 'direct'
  },
  {
    iso_id: '5.17.2',
    domain: '5. 조직 통제',
    control_no: '5.17',
    control_name: '인증 정보',
    check_item: '인증정보 사용시 이에 대한 로그를 증적으로 남기고 있습니까?',
    status: '적용',
    operation: '',
    evidence: '',
    policy: '',
    mapped_isms: [{"req_id": "2.5.2", "subject": "사용자 식별", "category": "인증 및 권한관리"}],
    mapping_confidence: 'direct'
  },
  {
    iso_id: '5.17.3',
    domain: '5. 조직 통제',
    control_no: '5.17',
    control_name: '인증 정보',
    check_item: '정보시스템 및 중요정보에 대한 사용자의 접근은 안전한 인증절차와 필요에 따라 강화된 인증방식을 적용하고 있습니까?',
    status: '적용',
    operation: '',
    evidence: '',
    policy: '',
    mapped_isms: [{"req_id": "2.5.2", "subject": "사용자 식별", "category": "인증 및 권한관리"}],
    mapping_confidence: 'direct'
  },
  {
    iso_id: '5.17.4',
    domain: '5. 조직 통제',
    control_no: '5.17',
    control_name: '인증 정보',
    check_item: '비밀번호 보호을 위해 효과적이고 유기적인 시설을 제공하는 비밀번호 관리 시스템이 운용되고 있습니까?',
    status: '적용',
    operation: '',
    evidence: '',
    policy: '',
    mapped_isms: [{"req_id": "2.5.2", "subject": "사용자 식별", "category": "인증 및 권한관리"}],
    mapping_confidence: 'direct'
  },
  {
    iso_id: '5.18.1',
    domain: '5. 조직 통제',
    control_no: '5.18',
    control_name: '접근 권한',
    check_item: '권한의 할당 및 사용을 관리하기위한 지침이 수립되어 있습니까?',
    status: '적용',
    operation: 'ㅇ 관련 지침을 통해 권한 할당 및 사용을 위한 절차를 수립하고 있음 ㅇ 주요 시스템 접근 시 SR 요청을 통해 사용자 계정 신청 후 권한 부여 및 생성하고 있음',
    evidence: '',
    policy: '- SG08_정보시스템보안지침_Ver 2.0   · 제14조(정보시스템 접근통제)   - SG05_계정관리지침_Ver 2.0   · 제10조(접근권한 부여)   · 제11조(접근권한 관리)',
    mapped_isms: [{"req_id": "2.5.3", "subject": "사용자 인증", "category": "인증 및 권한관리"}],
    mapping_confidence: 'direct'
  },
  {
    iso_id: '5.18.2',
    domain: '5. 조직 통제',
    control_no: '5.18',
    control_name: '접근 권한',
    check_item: '권한 사용시 이에 대한 로그를 증적으로 남기고 있습니까?',
    status: '적용',
    operation: '',
    evidence: '',
    policy: '',
    mapped_isms: [{"req_id": "2.5.3", "subject": "사용자 인증", "category": "인증 및 권한관리"}],
    mapping_confidence: 'direct'
  },
  {
    iso_id: '5.18.3',
    domain: '5. 조직 통제',
    control_no: '5.18',
    control_name: '접근 권한',
    check_item: '데이터나 정보 서비스에 대한 접근을 관리하기 위해서 정기적으로 접근권한에 대하여서 점검하며 시스템 관리자와 사용자의 권한을 명확히 구분하고 통제하고 있습니까?',
    status: '부분적용',
    operation: '',
    evidence: '',
    policy: '',
    mapped_isms: [{"req_id": "2.5.3", "subject": "사용자 인증", "category": "인증 및 권한관리"}],
    mapping_confidence: 'partial'
  },
  {
    iso_id: '5.18.4',
    domain: '5. 조직 통제',
    control_no: '5.18',
    control_name: '접근 권한',
    check_item: '정보와 정보처리설비에 대한 모든 직원, 외부자의 접근권한은 고용, 계약, 협약의 종료 및 변경시 즉시 삭제를 하십니까?',
    status: '적용',
    operation: '',
    evidence: '',
    policy: '',
    mapped_isms: [{"req_id": "2.5.3", "subject": "사용자 인증", "category": "인증 및 권한관리"}],
    mapping_confidence: 'direct'
  },
  {
    iso_id: '5.19.1',
    domain: '5. 조직 통제',
    control_no: '5.19',
    control_name: '공급자 관계 정보보호',
    check_item: '정보보호 요구사항을 수립하여 공급자 협약을 진행하고 있습니까?',
    status: '적용',
    operation: 'ㅇ 정보보호 처리 위수탁 계약서 내 안전한 서비스 제공을 위한 내용이 포함되어 체결하고 있음',
    evidence: '- 수탁자 정보보호 관련 계약(샘플- 보안관제서비스)',
    policy: '- SG04_외부주문보안지침_Ver 2.0   · 제3장 외부업체 보안 관리   · 제4장 입찰 및 계약 시 보안 관리',
    mapped_isms: [{"req_id": "2.3.1", "subject": "외부자 현황 관리", "category": "외부자 보안"}],
    mapping_confidence: 'direct'
  },
  {
    iso_id: '5.20.1',
    domain: '5. 조직 통제',
    control_no: '5.20',
    control_name: '공급업체 계약 내 정보보호 문제 해결',
    check_item: '정보보호 요구사항을 공급자와 합의하여 문서화하고 있습니까?',
    status: '적용',
    operation: 'ㅇ 수탁자 대상으로 정보보호 관련 계약을 체결하고 운영하고 있음',
    evidence: '- 수탁자 정보보호 관련 계약(샘플- 보안관제서비스)',
    policy: '- SG04_외부주문보안지침_Ver 2.0   · 제3장 외부업체 보안 관리   · 제4장 입찰 및 계약 시 보안 관리',
    mapped_isms: [{"req_id": "2.3.2", "subject": "외부자 계약 시 보안", "category": "외부자 보안"}],
    mapping_confidence: 'direct'
  },
  {
    iso_id: '5.21.1',
    domain: '5. 조직 통제',
    control_no: '5.21',
    control_name: '정보통신기술(ICT) 공급망의 정보보호 관리',
    check_item: '공급자 협약 시 정보통신기술 서비스 및 공급망 관련 요구사항을 포함하고 있습니까?',
    status: '적용',
    operation: 'ㅇ 정보보호 처리 위수탁 계약서 내 안전한 서비스 제공을 위한 내용이 포함되어 체결하고 있음',
    evidence: '- 수탁자 정보보호 관련 계약(샘플- 보안관제서비스)',
    policy: '- SG04_외부주문보안지침_Ver 2.0   · 제3장 외부업체 보안 관리   · 제4장 입찰 및 계약 시 보안 관리',
    mapped_isms: [{"req_id": "2.3.2", "subject": "외부자 계약 시 보안", "category": "외부자 보안"}],
    mapping_confidence: 'direct'
  },
  {
    iso_id: '5.22.1',
    domain: '5. 조직 통제',
    control_no: '5.22',
    control_name: '공급업체 서비스의 모니터링, 검토 및 변경 관리',
    check_item: '공급자에 의해 제공되는 서비스, 보고서, 기록들은 정기적인 검토와 감사를 실시하고 있습니까?',
    status: '적용',
    operation: 'ㅇ 정보처리 수탁자 대상으로 수탁자 보안 점검 요청을 정기적으로 수행하고 있음',
    evidence: '- 수탁자 보안 점검 요청 메일(샘플-IDC)',
    policy: '- SG04_외부주문보안지침_Ver 2.0   · 제5장 수행 및 완료 시 보안 관리',
    mapped_isms: [{"req_id": "2.3.3", "subject": "외부자 보안 이행 관리", "category": "외부자 보안"}],
    mapping_confidence: 'direct'
  },
  {
    iso_id: '5.22.2',
    domain: '5. 조직 통제',
    control_no: '5.22',
    control_name: '공급업체 서비스의 모니터링, 검토 및 변경 관리',
    check_item: '서비스의 변경시 관련된 업무시스템 및 프로세스에 미치는 영향을 고려하여 운영되고 있습니까?',
    status: '적용',
    operation: '',
    evidence: '',
    policy: '',
    mapped_isms: [{"req_id": "2.3.3", "subject": "외부자 보안 이행 관리", "category": "외부자 보안"}],
    mapping_confidence: 'direct'
  },
  {
    iso_id: '5.23.1',
    domain: '5. 조직 통제',
    control_no: '5.23',
    control_name: '클라우드 서비스 이용을 위한 정보보호',
    check_item: '클라우드 서비스 제공자와 정보보호 및 개인정보보호에 대한 책임과 역할을 명확히 정의하고 이를 계약서(SLA 등)에 반영하고 있습니까?',
    status: '적용',
    operation: 'ㅇ 관련 매뉴얼을 통해 클라우드 서비스 이용 절차 및 보안 사항에 대해 정의하고 있음',
    evidence: '',
    policy: '- SPR03_클라우드 서비스 이용 매뉴얼_Ver 1.0',
    mapped_isms: [{"req_id": "2.3.1", "subject": "외부자 현황 관리", "category": "외부자 보안"}],
    mapping_confidence: 'direct'
  },
  {
    iso_id: '5.23.2',
    domain: '5. 조직 통제',
    control_no: '5.23',
    control_name: '클라우드 서비스 이용을 위한 정보보호',
    check_item: '클라우드 서비스 이용 시 서비스 유형에 따른 보안위험을 평가하여 비인가 접근, 설정오류 등을 방지할 수 있도록 보안 구성 및 설정 기준, 보안설정 변경 및 승인 절차, 안전한 접속방법, 권한 체계 등 보안 통제 정책을 수립 및 이행하고 있습니까?',
    status: '적용',
    operation: '',
    evidence: '',
    policy: '',
    mapped_isms: [{"req_id": "2.3.1", "subject": "외부자 현황 관리", "category": "외부자 보안"}],
    mapping_confidence: 'direct'
  },
  {
    iso_id: '5.23.3',
    domain: '5. 조직 통제',
    control_no: '5.23',
    control_name: '클라우드 서비스 이용을 위한 정보보호',
    check_item: '클라우드 서비스 관리자 권한은 역할에 따라 최소화하여 부여하고 관리자 권한에 대한 비인가 접근, 권한 오남용 등을 방지할 수 있도록 강화된 인증, 암호화, 접근 통제, 감사기록 등 보호대책을 적용하고 있습니까?',
    status: '적용',
    operation: '',
    evidence: '',
    policy: '',
    mapped_isms: [{"req_id": "2.3.1", "subject": "외부자 현황 관리", "category": "외부자 보안"}],
    mapping_confidence: 'direct'
  },
  {
    iso_id: '5.23.4',
    domain: '5. 조직 통제',
    control_no: '5.23',
    control_name: '클라우드 서비스 이용을 위한 정보보호',
    check_item: '클라우드 서비스의 보안 설정 변경, 운영 현황 등을 모니터링하고 그 적절성을 정기적으로 검토하고 있습니까?',
    status: '적용',
    operation: '',
    evidence: '',
    policy: '',
    mapped_isms: [{"req_id": "2.3.1", "subject": "외부자 현황 관리", "category": "외부자 보안"}],
    mapping_confidence: 'direct'
  },
  {
    iso_id: '5.24.1',
    domain: '5. 조직 통제',
    control_no: '5.24',
    control_name: '정보보호 사고 관리 계획 및 준비',
    check_item: '보안사고 대응계획을 위한 절차가  수립되어 있습니까? - 보안사고의 정의 및 범위 - 보안사고 발생시 보고 및 대응 절차 - 사고 복구조직의구성 - 교육계획 등',
    status: '적용',
    operation: 'ㅇ 침해사고 및 개인정보 유출사고에 대응하기 위한 \'침해사고대응지침\'을 수립하고 있으며, 상세한 침해사고 대응절차, 보고체계, 대응방안 등을 \'침해사고 대응 매뉴얼\'에 정의하여 운영하고 있음',
    evidence: '',
    policy: '- SG13_침해사고 대응지침_Ver 2.0   · 제6조(사고관리계획 수립)   · 제7조(침해사고 보고 및 대응) - SPR01_침해사고 대응 매뉴얼_Ver 1.0',
    mapped_isms: [{"req_id": "2.11.1", "subject": "사고 예방 및 대응체계 구축", "category": "사고 예방 및 대응"}],
    mapping_confidence: 'direct'
  },
  {
    iso_id: '5.24.2',
    domain: '5. 조직 통제',
    control_no: '5.24',
    control_name: '정보보호 사고 관리 계획 및 준비',
    check_item: '보안사고의 모니터링, 대응 및 처리와 관련되어 전문가, 전문기관, 전문정부기관 등과의 협조체계를 구축하고 있습니까?',
    status: '적용',
    operation: '',
    evidence: '',
    policy: '',
    mapped_isms: [{"req_id": "2.11.1", "subject": "사고 예방 및 대응체계 구축", "category": "사고 예방 및 대응"}],
    mapping_confidence: 'direct'
  },
  {
    iso_id: '5.24.3',
    domain: '5. 조직 통제',
    control_no: '5.24',
    control_name: '정보보호 사고 관리 계획 및 준비',
    check_item: '보안사고를 모니터링하고 대응할 수 있는 다음과 같은 사항을 포함한 중앙 집중적인 대응체계가 구축되어 있습니까? - 중요도에 따른 보안사고 분류, 보고체계 및 대응요령  - 모니터링 및 대응 방법 - 대응 조직 및 인력 - 모니터링 및 대응 절차 - 모니터링 및 대응 보고 및 승인 방법',
    status: '적용',
    operation: '',
    evidence: '',
    policy: '',
    mapped_isms: [{"req_id": "2.11.1", "subject": "사고 예방 및 대응체계 구축", "category": "사고 예방 및 대응"}],
    mapping_confidence: 'direct'
  },
  {
    iso_id: '5.25.1',
    domain: '5. 조직 통제',
    control_no: '5.25',
    control_name: '정보보호 사건에 대한 평가 및 결정',
    check_item: '정보보호 이벤트 발생을 대비하여 정보보호 사고 분류 기준을 정의하고 있습니까?',
    status: '적용',
    operation: 'ㅇ 관련 지침 및 매뉴얼을 통해 정보보호 관련 이벤트에 대한 분류 기준을 정의하고 있음',
    evidence: '',
    policy: '- SG13_침해사고 대응지침_Ver 2.0   · 제8조(침해사고 유형) - SPR01_침해사고 대응 매뉴얼_Ver 1.0',
    mapped_isms: [{"req_id": "2.11.2", "subject": "취약점 점검 및 조치", "category": "사고 예방 및 대응"}],
    mapping_confidence: 'direct'
  },
  {
    iso_id: '5.26.1',
    domain: '5. 조직 통제',
    control_no: '5.26',
    control_name: '정보보호 사고 대응',
    check_item: '정보보호 사고를 대비한 대응 절차를 문서화하고 있습니까?',
    status: '적용',
    operation: 'ㅇ \'침해사고 대응 매뉴얼\'을 통해 정보보호 사고를 대비한 대응 절차를 문서화 하고 있음',
    evidence: '',
    policy: '- SG13_침해사고 대응지침_Ver 2.0   · 제14조(침해사고 대응 및 복구) - SPR01_침해사고 대응 매뉴얼_Ver 1.0',
    mapped_isms: [{"req_id": "2.11.3", "subject": "이상행위 분석 및 모니터링", "category": "사고 예방 및 대응"}],
    mapping_confidence: 'direct'
  },
  {
    iso_id: '5.27.1',
    domain: '5. 조직 통제',
    control_no: '5.27',
    control_name: '정보보호 사고로 부터 학습',
    check_item: '보안사고가 처리되고 종결된 후 이에 대한 분석을 이행하고 있으며, 그 결과를 보고하고 있습니까? - 보안사고날짜 - 보고자와 보고일시 - 사고내용 - 사고 대응내용 - 보안사고 통계 등',
    status: '적용',
    operation: 'ㅇ 침해사고가 발생한 건이 없으며, 심각한 침해사고 발생시 최고경영층까지 신속하게 보고할 수 있도록 체계가 구축되어 있음 ㅇ 침해사고 시 상세한 침해사고 보고를 위해 \'침해사고대응지침\' 내 침해사고보고서에 사고 시간, 사고 내용 등 필요 내용을 모두 포함하고 있음 ㅇ 침해사고 발생 시 관련 법률 및 규정에 따라 유관기관에 신고, 통지할 수 있도록 체계가',
    evidence: '',
    policy: '- SG13_침해사고 대응지침_Ver 2.0   · 제15조(침해사고 기록 및 보고) - SPR01_침해사고 대응 매뉴얼_Ver 1.0',
    mapped_isms: [{"req_id": "2.11.4", "subject": "사고 대응 훈련 및 개선", "category": "사고 예방 및 대응"}],
    mapping_confidence: 'direct'
  },
  {
    iso_id: '5.27.2',
    domain: '5. 조직 통제',
    control_no: '5.27',
    control_name: '정보보호 사고로 부터 학습',
    check_item: '보안사고처리후 재발 방지를 위한 훈련이 정기적으로 실시되도록 계획이 있습니까?  - 발생할 수 있는 사고 내용 - 대응방안 - 향후 재발방지 방안',
    status: '적용',
    operation: '',
    evidence: '',
    policy: '',
    mapped_isms: [{"req_id": "2.11.4", "subject": "사고 대응 훈련 및 개선", "category": "사고 예방 및 대응"}],
    mapping_confidence: 'direct'
  },
  {
    iso_id: '5.27.3',
    domain: '5. 조직 통제',
    control_no: '5.27',
    control_name: '정보보호 사고로 부터 학습',
    check_item: '보안사고로부터 얻은 정보를 활용하여, 유사 사고가 반복되지 않도록 재발방지 대책 및 교육 계획을 수립하고 있습니까?  - 정보보호 사고 교육 - 정책, 절차, 조직 등의 보안체계에 대한 변경 등',
    status: '적용',
    operation: '',
    evidence: '',
    policy: '',
    mapped_isms: [{"req_id": "2.11.4", "subject": "사고 대응 훈련 및 개선", "category": "사고 예방 및 대응"}],
    mapping_confidence: 'direct'
  },
  {
    iso_id: '5.28.1',
    domain: '5. 조직 통제',
    control_no: '5.28',
    control_name: '증거 수집',
    check_item: '다음과 같은 내용을 반영한 보안사고처리 및 복구 절차가 존재합니까? - 증거자료의 수집 - 취약성의 제거 등 사후관리 - 재발방지를 위한 기타사항',
    status: '적용',
    operation: 'ㅇ 침해사고 시 상세한 침해사고 보고를 위해 \'침해사고대응지침\' 내 침해사고보고서에 사고 시간, 사고 내용 등 필요 내용을 모두 포함하고 있음  ㅇ 침해사고 발생 시 관련 법률 및 규정에 따라 유관기관에 신고, 통지할 수 있도록 체계가 구축되어 있음  ㅇ 실제 침해사고 발생 시 분석을 통해 얻어진 정보를 활용하여 재발방지 대책을 세우고, 결과를 바탕으로',
    evidence: '',
    policy: '- SG13_침해사고 대응지침_Ver 2.0   · 제14조(침해사고 대응 및 복구) - SPR01_침해사고 대응 매뉴얼_Ver 1.0',
    mapped_isms: [{"req_id": "2.11.1", "subject": "사고 예방 및 대응체계 구축", "category": "사고 예방 및 대응"}],
    mapping_confidence: 'direct'
  },
  {
    iso_id: '5.28.2',
    domain: '5. 조직 통제',
    control_no: '5.28',
    control_name: '증거 수집',
    check_item: '보안사고 처리 후 민형사상 법적 조치나 조직 및 개인에 대한 소송의 지원을 위해 적정한 증거자료를 확보, 유지관리하고 있습니까?',
    status: '적용',
    operation: '',
    evidence: '',
    policy: '',
    mapped_isms: [{"req_id": "2.11.1", "subject": "사고 예방 및 대응체계 구축", "category": "사고 예방 및 대응"}],
    mapping_confidence: 'direct'
  },
  {
    iso_id: '5.29.1',
    domain: '5. 조직 통제',
    control_no: '5.29',
    control_name: '중단 중 정보보호',
    check_item: '조직은 위기 또는 재난과 같이 어려운 상황에서 정보보호와 정보보호 관리의 연속성에 대한 요구사항을 결정하고 있습니까?',
    status: '적용',
    operation: 'ㅇ 업무연속성에 대한 요구사항을 결정하고 있으며, \'IT 재해복구지침\' 및 대응매뉴얼 내 대응조직, 비상연락체계, 복구순서 및 전략 수립 등을 통해 IT 재해복구 체계를 구축하고 있음',
    evidence: '',
    policy: '- SG18_사업연속성관리 지침_Ver 1.0   · 제5장 재난 대응 절차',
    mapped_isms: [{"req_id": "2.12.1", "subject": "재해∙재난 대비 안전조치", "category": "재해복구"}],
    mapping_confidence: 'direct'
  },
  {
    iso_id: '5.29.2',
    domain: '5. 조직 통제',
    control_no: '5.29',
    control_name: '중단 중 정보보호',
    check_item: '조직은 어려운 상황에서 정보보호에 필요한 수준의 연속성을 보장하기 위하여 프로세스, 절차, 통제를 수립하고 문서화하여 구현 및 유지하고 있습니까?',
    status: '적용',
    operation: '',
    evidence: '',
    policy: '',
    mapped_isms: [{"req_id": "2.12.1", "subject": "재해∙재난 대비 안전조치", "category": "재해복구"}],
    mapping_confidence: 'direct'
  },
  {
    iso_id: '5.29.3',
    domain: '5. 조직 통제',
    control_no: '5.29',
    control_name: '중단 중 정보보호',
    check_item: '조직이 수립하고 구현한 정보보호 연속성 통제가 어려운 상황에 적절하고 효과적임을 보장하기 위하여 주기적으로 검증하고 있습니까?',
    status: '적용',
    operation: '',
    evidence: '',
    policy: '',
    mapped_isms: [{"req_id": "2.12.1", "subject": "재해∙재난 대비 안전조치", "category": "재해복구"}],
    mapping_confidence: 'direct'
  },
  {
    iso_id: '5.30.1',
    domain: '5. 조직 통제',
    control_no: '5.30',
    control_name: '비즈니스 연속성을 위한 ICT 준비',
    check_item: '조직의 핵심 서비스(업무) 연속성을 위협할 수 있는 IT 재해 유형을 식별하고, 유형별 피해규모 및 업무에 미치는 영향을 분석하여 핵심 IT 서비스(업무) 및 시스템을 식별하고 있는가?',
    status: '적용',
    operation: 'ㅇ 2024년 침해사고 모의 훈련임 스팸 메일 훈련을 수행하였으며, 2025년 훈련 예정',
    evidence: '- 침해사고 대응 및 복구훈련 결과(악성코드 훈련)',
    policy: '- SG14_IT재해복구지침_Ver 2.0   · 제5장 IT재해복구 모의훈련 - SG18_사업연속성관리 지침_Ver 1.0   · 제8장 모의훈련 - SPR01_침해사고 대응 매뉴얼_Ver 1.0',
    mapped_isms: [{"req_id": "2.12.2", "subject": "재해 복구 시험 및 개선", "category": "재해복구"}],
    mapping_confidence: 'direct'
  },
  {
    iso_id: '5.30.2',
    domain: '5. 조직 통제',
    control_no: '5.30',
    control_name: '비즈니스 연속성을 위한 ICT 준비',
    check_item: '핵심 IT 서비스 및 시스템의 중요도 및 특성에 따른 복구 목표시간, 복구 목표시점을 정의하고 있는가?',
    status: '적용',
    operation: '',
    evidence: '',
    policy: '',
    mapped_isms: [{"req_id": "2.12.2", "subject": "재해 복구 시험 및 개선", "category": "재해복구"}],
    mapping_confidence: 'direct'
  },
  {
    iso_id: '5.30.3',
    domain: '5. 조직 통제',
    control_no: '5.30',
    control_name: '비즈니스 연속성을 위한 ICT 준비',
    check_item: '재해·재난 발생 시에도 핵심 서비스 및 시스템의 연속성을 보장할 수 있도록 복구 전략 및 대책, 비상시 복구 조직, 비상연락체계, 복구 절차 등 재해 복구 계획을 수립·이행하고 있는가?',
    status: '적용',
    operation: '',
    evidence: '',
    policy: '',
    mapped_isms: [{"req_id": "2.12.2", "subject": "재해 복구 시험 및 개선", "category": "재해복구"}],
    mapping_confidence: 'direct'
  },
  {
    iso_id: '5.31.1',
    domain: '5. 조직 통제',
    control_no: '5.31',
    control_name: '적용 법규 및 계약 요구사항 식별',
    check_item: '정보시스템에 대해 관련된 모든 법, 규제, 계약, 정책, 기술상의 요구사항을 정의하고 문서화하고 있습니까?  - 산업기술의 유출방지 및 보호에 관한 법률  - 정보통신망 이용 촉진 및 정보보호 등에 관한 법률  - 개인정보보호법  - 부정경쟁방지 및 영업비밀보호에 관한 법률  - 상기 법률 하위문서 및 매뉴얼 등',
    status: '적용',
    operation: 'ㅇ 조직이 준수해야 하는 정보보호 관련 법적 요구사항을 파악하고 최신성을 유지하고 있음',
    evidence: '',
    policy: '- SP01_정보보호규정_Ver 2.0   · 제4조(관련 법규)',
    mapped_isms: [{"req_id": "2.1.1", "subject": "정책의 유지관리", "category": "정책, 조직, 자산 관리"}],
    mapping_confidence: 'direct'
  },
  {
    iso_id: '5.32.1',
    domain: '5. 조직 통제',
    control_no: '5.32',
    control_name: '지적 재산권',
    check_item: '지적자산의 권리를 존중하여야하는 자료 및 소프트웨어 제품 재산의 사용에 있어서 법률적인 제한에 부합하도록 절차가 구현되어 있습니까?',
    status: '적용',
    operation: 'ㅇ 관련 지침 등으로 불법 소프트웨어 등을 사용하지 않도록 규정하고 있음',
    evidence: '',
    policy: '- SG07_단말 보안지침_Ver 2.0   · 제7조(단말기 보호대책)   · 제14조(비인가 소프트웨어 통제)',
    mapped_isms: [{"req_id": "2.1.1", "subject": "정책의 유지관리", "category": "정책, 조직, 자산 관리"}],
    mapping_confidence: 'direct'
  },
  {
    iso_id: '5.33.1',
    domain: '5. 조직 통제',
    control_no: '5.33',
    control_name: '기록 보호',
    check_item: '중요한 기록들은 손실, 파괴, 위조로부터 보호되도록 절차가 수립되어 있습니까?',
    status: '적용',
    operation: 'ㅇ 중요 문서 및 정보는 백업 관리하고 있음. ㅇ 주요 서비스의 경우 AWS 클라우드 서비스 및 다중 가용영역을 사용하고 있음',
    evidence: '',
    policy: '- SG01_개인(신용)정보보호지침_Ver 2.0   · 제49조(접속기록의 보관 및 점검)   · 제50조(업무처리기록의 보존)',
    mapped_isms: [{"req_id": "2.1.2", "subject": "조직의 유지관리", "category": "정책, 조직, 자산 관리"}],
    mapping_confidence: 'direct'
  },
  {
    iso_id: '5.34.1',
    domain: '5. 조직 통제',
    control_no: '5.34',
    control_name: '프라이버시와 개인정보보호',
    check_item: '관련법률에 따라 데이터 보호 및 개인정보를 보호, 관리하고 있습니까?',
    status: '적용',
    operation: 'ㅇ 개인정보보호법 및 신용정보보호법에 따른 개인정보 보호를 위해 관련 규정 및 지침을 수립하고 이행하고 있음',
    evidence: '',
    policy: '- SP01_정보보호규정_Ver 2.0   · 제4조(관련 법규) - SP02_개인(신용)정보보호규정_Ver 2.0   · 제3조(관련 법규)',
    mapped_isms: [{"req_id": "3.3.1", "subject": "개인정보 제3자 제공", "category": "개인정보 제공 시 보호조치"}],
    mapping_confidence: 'direct'
  },
  {
    iso_id: '5.35.1',
    domain: '5. 조직 통제',
    control_no: '5.35',
    control_name: '정보보호에 대한 독립적인 검토',
    check_item: '정보보호 위원회는 정책 및 절차 등에 관하여 정기적 혹은 중대한 변화가 발생할 경우 독립적으로 검토활동을 수행하는가?',
    status: '적용',
    operation: 'ㅇ 정보보호 위원회를 통해 중요 변화에 대한 검토를 수행하고 정보보호관리체계 내 반영되도록 하고 있음',
    evidence: '- 2025년 제2차 정보보호 위원회 보고 내역',
    policy: '- SP01_정보보호규정_Ver2.0   · 제7조(정보보호 위원회) - SG02_정보보호조직지침_Ver 2.0   · 제3장 정보보호위원회 - SG16_보안점검 및 감사 지침_Ver 1.0   · 제3조(보안감사의 목적)   · 제4조(보안감사의 범위)',
    mapped_isms: [{"req_id": "1.1.3", "subject": "조직 구성", "category": "관리체계 기반 마련"}],
    mapping_confidence: 'direct'
  },
  {
    iso_id: '5.36.1',
    domain: '5. 조직 통제',
    control_no: '5.36',
    control_name: '정보보호를 위한 정책, 규칙, 및 표준 준수',
    check_item: '모든 정보보호정책, 절차의 준수여부를 검토하고 있습니까?',
    status: '적용',
    operation: 'ㅇ 관리체계가 효과적으로 운영되는지 점검하기 위한 관리체계 점검기준, 범위, 점검인력 자격요건 등을 포함한 정보보호 감사 계획을 수립하고 있음',
    evidence: '- 2025년 IT 감사 계획서 - 2025년 IT 자체 감사 결과서',
    policy: '- SP01_정보보호규정_Ver 2.0   · 제3조(정책의 유지관리) - SG11_정보보안점검지침_Ver 2.0   · 제12조(이행점검) - SG16_보안점검 및 감사 지침_Ver 1.0   · 제3조(보안감사의 목적)   · 제4조(보안감사의 범위)',
    mapped_isms: [{"req_id": "1.4.1", "subject": "법적 요구사항 준수 검토", "category": "관리체계 점검 및 개선"}],
    mapping_confidence: 'direct'
  },
  {
    iso_id: '5.36.2',
    domain: '5. 조직 통제',
    control_no: '5.36',
    control_name: '정보보호를 위한 정책, 규칙, 및 표준 준수',
    check_item: '정보시스템이 정보보호표준 및 절차에 따라 운영 관리되고 있는지 정기적으로 보안감사를 실시하며 기술적 점검을 하고 있습니까?',
    status: '적용',
    operation: '',
    evidence: '',
    policy: '',
    mapped_isms: [{"req_id": "1.4.1", "subject": "법적 요구사항 준수 검토", "category": "관리체계 점검 및 개선"}],
    mapping_confidence: 'direct'
  },
  {
    iso_id: '5.37.1',
    domain: '5. 조직 통제',
    control_no: '5.37',
    control_name: '운영 절차 문서화',
    check_item: '보안 운영지침 및 절차가 수립되어 있으며 문서화 되어 있습니까?',
    status: '적용',
    operation: 'ㅇ 지침과 매뉴얼 문서를 통해 세부적인 방법 및 절차 등을 수립하고 있음 ㅇ 정보보호 정책 및 정책시행 문서를 최신본으로 관리하고 있으며, 제정·개정 시 그룹웨어를 통해 공유하고 있음',
    evidence: '',
    policy: '- SP01_정보보호규정_Ver 2.0   · 제3조(정책의 유지관리) - SG11_정보보안점검지침_Ver 2.0   · 제12조(이행점검) - SG16_보안점검 및 감사 지침_Ver 1.0   · 제3조(보안감사의 목적)   · 제4조(보안감사의 범위)',
    mapped_isms: [{"req_id": "2.12.1", "subject": "재해∙재난 대비 안전조치", "category": "재해복구"}],
    mapping_confidence: 'direct'
  },
  {
    iso_id: '6.1.1',
    domain: '5. 조직 통제',
    control_no: '6.1',
    control_name: '적격 심사',
    check_item: '계약직 및 임시직원은 물론 정식직원 채용 시 신원, 업무능력, 교육정도, 경력, 신원조사 등에 대한 적격심사가 이루어지고 있습니까?',
    status: '적용',
    operation: 'ㅇ 신규입사자 채용 시 경력 및 자격 검증을 수행하고 있으며, 자금세탁 방지 등을 위한 KYE(Know Your Employee)를 수행하고 있음 ㅇ 신규 입사 시 정보보호서약서를 징구하고 있음',
    evidence: '- 정보보호서약서(신규입사 시)',
    policy: '- SG03_인적보안지침_Ver 2.0   · 제4조(입사 시 보안관리)',
    mapped_isms: [],
    mapping_confidence: 'none'
  },
  {
    iso_id: '6.1.2',
    domain: '5. 조직 통제',
    control_no: '6.1',
    control_name: '적격 심사',
    check_item: '민감한직무(정보시스템 접근권한업무, 재무정보나 비밀정보 처리업무)담당자에 대해 강화된 적격심사나 직무순환을 실시하도록 규정되어 있으며 비밀취급인가, 보안 서약서 청구 등 보안대책이 수립되어 있으며 수행하고 있습니까?',
    status: '적용',
    operation: '',
    evidence: '',
    policy: '',
    mapped_isms: [],
    mapping_confidence: 'none'
  },
  {
    iso_id: '6.2.1',
    domain: '5. 조직 통제',
    control_no: '6.2',
    control_name: '고용 계약조건',
    check_item: '모든 직원, 계약자 및 제3자들은 비즈니스 정보를 보호해야 할 필요성과  책임을 포함한 비밀 계약 및 비공개 계약에 서명을 받고 있습니까?',
    status: '적용',
    operation: 'ㅇ 신규 입사 시 정보보호서약서를 징구하고 있음',
    evidence: '- 정보보호서약서(샘플)',
    policy: '- SG03_인적보안지침_Ver 2.0   · 제5조(보안서약서 징구 및 관리)',
    mapped_isms: [],
    mapping_confidence: 'none'
  },
  {
    iso_id: '6.3.1',
    domain: '5. 조직 통제',
    control_no: '6.3',
    control_name: '정보보호 인식, 교육 및 훈련',
    check_item: '(개인)정보보호 교육 기준을 수립 및 시행하고 있습니까?  - (개인)정보보호 교육 기준 및 연간 교육 계획 수립(임직원, 신규입사자, 외부인력)  - 일반 정보보안 교육과 전문 보안교육 구분(임직원 및 외부인력)  - 정기교육, 상시교육(연 1회 이상)',
    status: '적용',
    operation: 'ㅇ 전체 임직원 대상 매년 개인정보보호교육 및 정보보호교육을 수행하고 있음',
    evidence: '- 2025년도 정보보호 교육 계획서',
    policy: '- SG03_인적보안지침_Ver 2.0   · 제5장 정보보호 및 개인(신용)정보보호 교육',
    mapped_isms: [],
    mapping_confidence: 'none'
  },
  {
    iso_id: '6.3.2',
    domain: '5. 조직 통제',
    control_no: '6.3',
    control_name: '정보보호 인식, 교육 및 훈련',
    check_item: '(개인)정보보호 교육 결과 검토 및 분석 후 차년도 교육에 반영하고 있습니까?  - 교육만족도 조사  - 교육책임자에게 교육결과 보고',
    status: '적용',
    operation: 'ㅇ 2025년 규정 지침 개정에 따란 교육 만족도 조사 후 차년도 교육에 반영 예정',
    evidence: '',
    policy: '',
    mapped_isms: [],
    mapping_confidence: 'none'
  },
  {
    iso_id: '6.3.3',
    domain: '5. 조직 통제',
    control_no: '6.3',
    control_name: '정보보호 인식, 교육 및 훈련',
    check_item: '해킹 공격의 인지 및 대응, 정보보호 사고 발생 시 신속한 대응을 위해 정기적으로 정보보호 사고 대응 모의훈련을 계획 및 실시하고 있습니까?  - 해킹(메일) 대응 모의 훈련  - 전산망 침투 훈련 등',
    status: '적용',
    operation: 'ㅇ매년 정보보호 사고 대응 모의 훈련을 수행함',
    evidence: '',
    policy: '',
    mapped_isms: [],
    mapping_confidence: 'none'
  },
  {
    iso_id: '6.3.4',
    domain: '5. 조직 통제',
    control_no: '6.3',
    control_name: '정보보호 인식, 교육 및 훈련',
    check_item: '교육 및 훈련은 정보보호정책이나 절차 및 역할의 변경이 있는 경우에는 수시로 실시하고 이에 대한 기록을 남기고 있습니까?',
    status: '적용',
    operation: 'ㅇ 절차 및 역할의 변경이 있는 경우 수시로 실시하고 기록 함',
    evidence: '',
    policy: '',
    mapped_isms: [],
    mapping_confidence: 'none'
  },
  {
    iso_id: '6.4.1',
    domain: '5. 조직 통제',
    control_no: '6.4',
    control_name: '징계 절차',
    check_item: '법령 및 규정 위반, 보안사고 유발 등 상황 발생 시 범위에 따라 처벌할 수 있는 규정이 마련되어 있습니까?',
    status: '적용',
    operation: 'ㅇ 보안 의무 위반 시 제재에 대한 사항을 인적보안 지침을 통해 수립 및 운영하고 있음',
    evidence: '- 정보보호서약서(샘플)',
    policy: '- SG03_인적보안지침_Ver 2.0   · 제9조(보안 의무 위반 금지)   · 제10조(보안 의무 위반 시 제재)',
    mapped_isms: [],
    mapping_confidence: 'none'
  },
  {
    iso_id: '6.5.1',
    domain: '5. 조직 통제',
    control_no: '6.5',
    control_name: '고용 종료 및 직무변경 후의 책임',
    check_item: '고용계약의 변경(퇴사, 계약만료)시 비밀유지에 대하여 면담하여 환기시키고 있습니까? (인사 관련 규정 내 비밀 유지 서약 환기 내용 포함 여부 확인)',
    status: '적용',
    operation: 'ㅇ 퇴사 시 비밀유지서약서를 징구하고 있으며, 관련 계정 및 권한 회수를 수행하고 있음',
    evidence: '- 정보보호서약서(샘플) - 퇴직자 체크리스트 및 비밀유지서약서',
    policy: '- SG03_인적보안지침_Ver 2.0   · 제6조(퇴사 및 직무변경시 보안관리)',
    mapped_isms: [],
    mapping_confidence: 'none'
  },
  {
    iso_id: '6.6.1',
    domain: '5. 조직 통제',
    control_no: '6.6',
    control_name: '기밀유지 또는 비밀유지 협약',
    check_item: '정보보호에 대한 조직의 요구를 반영하는 기밀 유지 또는 비공개 계약은 직원 및 기타 관련 이해 당사자가 식별하고, 문서화하고, 정기적으로 검토하고 서명하고 있습니까?',
    status: '적용',
    operation: 'ㅇ 퇴사 시 비밀유지서약서를 징구하고 있으며, 관련 계정 및 권한 회수를 수행하고 있음',
    evidence: '- 퇴직자 체크리스트 및 비밀유지서약서',
    policy: '- SG03_인적보안지침_Ver 2.0   · 제5조(보안서약서 징구 및 관리)',
    mapped_isms: [],
    mapping_confidence: 'none'
  },
  {
    iso_id: '6.7.1',
    domain: '5. 조직 통제',
    control_no: '6.7',
    control_name: '원격 근무',
    check_item: '원격근무에 대한 정의, 허가 범위, 기술적 보호대책을 마련하고 있습니까?',
    status: '적용',
    operation: 'ㅇ 임직원 원격 근무 시, 안전한 단말기(FortiClient 등 필수)에서 VPN을 통해 접근하도록 하고 있음',
    evidence: '- 네트워크 구성도',
    policy: '- SG08_정보시스템보안지침_Ver 2.0   · 제15조(정보시스템 외부 접근)',
    mapped_isms: [],
    mapping_confidence: 'none'
  },
  {
    iso_id: '6.8.1',
    domain: '5. 조직 통제',
    control_no: '6.8',
    control_name: '정보보호 이벤트 보고',
    check_item: '임직원이 관찰되거나 의심되는 정보보호 사건, 시스템 이벤트 등을 적절한 채널을 통해 적시에 보고할 수 있는 메커니즘을 제공하고 있습니까?',
    status: '적용',
    operation: 'ㅇ 당사는 보안 이벤트 보고 절차를 마련하여, 임직원이 의심스러운 이메일, 악성코드 감염 등의 이상 징후를 발견 시 즉시 정보보안팀 Slack 채널 등을 통해 보고하도록 하고 있음 ㅇ 대외 서비스에 대한 공격 및 이상행위 탐지를 WAF 등을 통해 탐지 및 대응하고 있음 ㅇ 내부자의 이상행위 등을 엑소스피어를 통해 모니터링하고 있음  - DLP 기능을 통한 ',
    evidence: '- 침해사고 신고 채널(Slack)',
    policy: '- SG13_침해사고 대응지침_Ver 2.0   · 제11조(침해사고 탐지)   · 제12조(침해사고 신고 및 접수) - SG08_정보시스템보안지침_Ver 2.0   · 제17조(로그 분석 및 모니터링)   · 제18조(침해시도 모니터링) - SPR01_침해사고 대응 매뉴얼_Ver 1.0',
    mapped_isms: [],
    mapping_confidence: 'none'
  },
  {
    iso_id: '6.8.2',
    domain: '5. 조직 통제',
    control_no: '6.8',
    control_name: '정보보호 이벤트 보고',
    check_item: '정보시스템의 보안사고의 징후 또는 보안사고 발생을 인지한 경우, 보안 취약점과 소프트웨어 기능 장애가 발생한 경우, 정의된 보안사고 보고절차에 의해 보고가 이루어지고 있습니까?',
    status: '적용',
    operation: 'ㅇ 침해사고 대응 지침에 따라 금융 당국에 신고 함',
    evidence: '',
    policy: '',
    mapped_isms: [],
    mapping_confidence: 'none'
  },
  {
    iso_id: '7.1.1',
    domain: '7. 물리적 통제',
    control_no: '7.1',
    control_name: '물리적 보호 경계',
    check_item: '각 구역별(보호구역) 정의 및 보안등급 지정이 규정화가 되어 있습니까?(제한구역, 통제구역 등의 설정)',
    status: '적용',
    operation: 'ㅇ 접견구역, 제한구역, 통제구역을 규정하고 있으며, 각 보호구역 별 통제가 되어있음.  - 제한구역 : 사무실 구역  - 통제구역 : 평촌 IDC, 4층 전산실',
    evidence: '',
    policy: '- SG06_물리적보안지침_Ver 2.0   · 제6조(보호구역의 지정)   · 제7조(제한구역 통제)   · 제8조(통제구역 통제) - SPR04_보호구역 출입절차서_Ver 1.0',
    mapped_isms: [{"req_id": "2.4.1", "subject": "보호구역 지정", "category": "물리 보안"}],
    mapping_confidence: 'direct'
  },
  {
    iso_id: '7.1.2',
    domain: '7. 물리적 통제',
    control_no: '7.1',
    control_name: '물리적 보호 경계',
    check_item: '각 보호구역(제한구역, 통제구역 등)별 보호대책이 수립(규정화, 문서화)되어 있으며 구현되고 있습니까?  -구역별 식별 라벨 부착  -출입통제 장비설치(카드키 등)  -외부자 방문증 규격화 및 패용, 인력 배치  -출입관리대장 관리  -출입자 및 출입기록에 대한 주기적 검토  -출입자 명단작성  -보호구역내의 작업에 대한 지침',
    status: '적용',
    operation: 'ㅇ 각 보호구역(제한구역, 통제구역 등)별 보호대책이 수립(규정화, 문서화)되어 있으며 구현되어 있음',
    evidence: '',
    policy: '',
    mapped_isms: [{"req_id": "2.4.1", "subject": "보호구역 지정", "category": "물리 보안"}],
    mapping_confidence: 'direct'
  },
  {
    iso_id: '7.2.1',
    domain: '7. 물리적 통제',
    control_no: '7.2',
    control_name: '물리적 진입',
    check_item: '보호구역 출입은 적절한 출입통제 절차에 의해 이루어지고 있습니까?',
    status: '적용',
    operation: 'ㅇ 보호구역 출입통제 절차서를 수립하여 운영하고 있음. ㅇ 물리적으로 보호구역을 분리하고 있으며, 건물의 출입통제 시스템을 통해 인가된 인원만 접근 가능하도록 통제하고 있음',
    evidence: '',
    policy: '- SG06_물리적보안지침_Ver 2.0   · 제6조(보호구역의 지정)   · 제7조(제한구역 통제)   · 제8조(통제구역 통제) - SPR04_보호구역 출입절차서_Ver 1.0',
    mapped_isms: [{"req_id": "2.4.2", "subject": "출입통제", "category": "물리 보안"}],
    mapping_confidence: 'direct'
  },
  {
    iso_id: '7.2.2',
    domain: '7. 물리적 통제',
    control_no: '7.2',
    control_name: '물리적 진입',
    check_item: '보호구역 출입자는 식별되고 기록, 관리되어 지고 있습니까?',
    status: '적용',
    operation: '',
    evidence: '',
    policy: '',
    mapped_isms: [{"req_id": "2.4.2", "subject": "출입통제", "category": "물리 보안"}],
    mapping_confidence: 'direct'
  },
  {
    iso_id: '7.2.3',
    domain: '7. 물리적 통제',
    control_no: '7.2',
    control_name: '물리적 진입',
    check_item: '보호구역 출입자 기록대장은 정기적으로 점검되고 있습니까?',
    status: '부분적용',
    operation: '',
    evidence: '',
    policy: '',
    mapped_isms: [{"req_id": "2.4.2", "subject": "출입통제", "category": "물리 보안"}],
    mapping_confidence: 'partial'
  },
  {
    iso_id: '7.2.4',
    domain: '7. 물리적 통제',
    control_no: '7.2',
    control_name: '물리적 진입',
    check_item: '보호구역 분류에 따른 적절한 보안대책이 수립되어 있습니까?',
    status: '적용',
    operation: '',
    evidence: '',
    policy: '',
    mapped_isms: [{"req_id": "2.4.2", "subject": "출입통제", "category": "물리 보안"}],
    mapping_confidence: 'direct'
  },
  {
    iso_id: '7.2.5',
    domain: '7. 물리적 통제',
    control_no: '7.2',
    control_name: '물리적 진입',
    check_item: '배송 및 하역 구역과 비인가자의 접근 가능 지역 등이 지정되어 있어서 정보처리설비로부터 격리되어 있습니까?',
    status: '적용',
    operation: '',
    evidence: '',
    policy: '',
    mapped_isms: [{"req_id": "2.4.2", "subject": "출입통제", "category": "물리 보안"}],
    mapping_confidence: 'direct'
  },
  {
    iso_id: '7.3.1',
    domain: '7. 물리적 통제',
    control_no: '7.3',
    control_name: '사무실, 방, 시설에 대한 보호',
    check_item: '사무실, 방, 설비에 대한 물리적 보호대책이 수립되어 있으며 이행되어있습니까?',
    status: '적용',
    operation: 'ㅇ 물리적 보안지침을 통해 물리적 보호를 위한 규정 및 대책을 수립 및 운영하고 있음 ㅇ 사무실 등 보호구역 출입 시 출입관리시스템 등의 보호대책을 수립되어 있음',
    evidence: '',
    policy: '- SG06_물리적보안지침_Ver 2.0   · 제6조(보호구역의 지정)   · 제7조(제한구역 통제) - SPR04_보호구역 출입절차서_Ver 1.0',
    mapped_isms: [{"req_id": "2.4.3", "subject": "정보시스템 보호", "category": "물리 보안"}],
    mapping_confidence: 'direct'
  },
  {
    iso_id: '7.4.1',
    domain: '7. 물리적 통제',
    control_no: '7.4',
    control_name: '물리적 보호 모니터링',
    check_item: '출입기록을 일정기간 보존하여 사후 모니터링이 가능하도록 문서적 또는 전자적으로 보존하고 있습니까?',
    status: '부분적용',
    operation: 'ㅇ 출입기록을 3년간 보관하고 있으며, 정기적으로 출입기록에 대한 검토를 수행하고 있음',
    evidence: '- 통제구역 출입관리 대장 - 세콤 출입기록 로그',
    policy: '- SG06_물리적보안지침_Ver 2.0   · 제7조(제한구역 통제)   · 제11조(전산실 등에 관한 사항) - SPR04_보호구역 출입절차서_Ver 1.0',
    mapped_isms: [{"req_id": "2.4.4", "subject": "보호설비 운영", "category": "물리 보안"}],
    mapping_confidence: 'partial'
  },
  {
    iso_id: '7.4.2',
    domain: '7. 물리적 통제',
    control_no: '7.4',
    control_name: '물리적 보호 모니터링',
    check_item: '주기적으로 비인가자 출입 시도, 장기 미출입자, 과도한 출입권한 부여 등을 확인하여 그 사유를 확인하고 조치하여 검토하고 있습니까?',
    status: '부분적용',
    operation: '',
    evidence: '',
    policy: '',
    mapped_isms: [{"req_id": "2.4.4", "subject": "보호설비 운영", "category": "물리 보안"}],
    mapping_confidence: 'partial'
  },
  {
    iso_id: '7.4.3',
    domain: '7. 물리적 통제',
    control_no: '7.4',
    control_name: '물리적 보호 모니터링',
    check_item: '보호구역에 대한 관제가 이루어지고 있습니까?',
    status: '부분적용',
    operation: '',
    evidence: '',
    policy: '',
    mapped_isms: [{"req_id": "2.4.4", "subject": "보호설비 운영", "category": "물리 보안"}],
    mapping_confidence: 'partial'
  },
  {
    iso_id: '7.5.1',
    domain: '7. 물리적 통제',
    control_no: '7.5',
    control_name: '물리적 및 환경적 위협으로부터 보호',
    check_item: '보호구역은 물리적, 환경적 위험이 적은 곳에 위치하고 있습니까?',
    status: '적용',
    operation: 'ㅇ 당사는 AWS 클라우드(AWS 서울 리전, 가용영역 다중화) 및 LG U+ 평촌 IDC(코로케이션 서비스)를 이용하고 있으며, 각 시설은 24x7 출입통제, CCTV 감시, 이중 전원, UPS, 소화설비 등 물리적·환경적 위협에 대비한 보호 통제가 적용되어 있음',
    evidence: '- 평촌 IDC 정보',
    policy: '- SG06_물리적보안지침_Ver 2.0   · 제10조(전원, 공조 등 설비에 관한 사항)   · 제11조(전산실 등에 관한 사항) - SPR04_보호구역 출입절차서_Ver 1.0',
    mapped_isms: [{"req_id": "2.4.2", "subject": "출입통제", "category": "물리 보안"}],
    mapping_confidence: 'direct'
  },
  {
    iso_id: '7.5.2',
    domain: '7. 물리적 통제',
    control_no: '7.5',
    control_name: '물리적 및 환경적 위협으로부터 보호',
    check_item: '화재ㆍ수재 등의 각종 재해에 대비한 시설을 충분히 설치하고 있습니까?',
    status: '적용',
    operation: '',
    evidence: '',
    policy: '',
    mapped_isms: [{"req_id": "2.4.2", "subject": "출입통제", "category": "물리 보안"}],
    mapping_confidence: 'direct'
  },
  {
    iso_id: '7.5.3',
    domain: '7. 물리적 통제',
    control_no: '7.5',
    control_name: '물리적 및 환경적 위협으로부터 보호',
    check_item: '각종 재해에 대비한 물리적 접근통제 및 시건장치를 설치하였습니까?',
    status: '적용',
    operation: '',
    evidence: '',
    policy: '',
    mapped_isms: [{"req_id": "2.4.2", "subject": "출입통제", "category": "물리 보안"}],
    mapping_confidence: 'direct'
  },
  {
    iso_id: '7.6.1',
    domain: '7. 물리적 통제',
    control_no: '7.6',
    control_name: '보호 영역에서 작업',
    check_item: '보안구역 내 작업 시 물리적 보호 절차와 가이드라인이 설계되어 적용되고 있으며, 자료유출 방지를 위한 보안대책이 수립되어 있으며 시행되고 있습니까?',
    status: '적용',
    operation: 'ㅇ 보호 구역에서 작업 시 출입 절차 및 물리적보안지침에 따라 작업을 수행하고 있음.',
    evidence: '',
    policy: '- SG06_물리적보안지침_Ver 2.0   · 제8조(통제구역 통제)   · 제13조(반출∙입 관리) - SPR04_보호구역 출입절차서_Ver 1.0',
    mapped_isms: [{"req_id": "2.4.3", "subject": "정보시스템 보호", "category": "물리 보안"}],
    mapping_confidence: 'direct'
  },
  {
    iso_id: '7.7.1',
    domain: '7. 물리적 통제',
    control_no: '7.7',
    control_name: '깨끗한 책상과 깨끗한 화면',
    check_item: '책상 위에 중요한 문서나 저장 매체를 남겨두지 않도록 하는 지침을 보유하고 있습니까?',
    status: '적용',
    operation: 'ㅇ 개인 업무 환경에 대한 보안 정책을 수립 및 운영하고 있음 ㅇ 사용자 보안 수칙을 통해 클린 데스크 보안 주기적 교육 수행',
    evidence: '- 사용자 보안 수칙',
    policy: '- SG06_물리적보안지침_Ver 2.0   · 제14조(개인업무환경 보안)   · 제15조(공용업무 환경 보안)',
    mapped_isms: [{"req_id": "2.5.4", "subject": "비밀번호 관리", "category": "인증 및 권한관리"}],
    mapping_confidence: 'direct'
  },
  {
    iso_id: '7.7.2',
    domain: '7. 물리적 통제',
    control_no: '7.7',
    control_name: '깨끗한 책상과 깨끗한 화면',
    check_item: '통상 근무시간 동안이나 그 외의 시간에 비인가된 자에 의한 정보접근, 손상을 방지하기 위하여 컴퓨터 화면에 정보처리에 관한 사항을 남겨놓지 않도록 하고 있습니까?',
    status: '적용',
    operation: 'ㅇ 개인 업무 환경에 대한 보안 정책을 수립 및 운영하고 있음 ㅇ 사용자 보안 수칙을 통해 클린 데스크 보안 주기적 교육 수행',
    evidence: '- 사용자 보안 수칙',
    policy: '',
    mapped_isms: [{"req_id": "2.5.4", "subject": "비밀번호 관리", "category": "인증 및 권한관리"}],
    mapping_confidence: 'direct'
  },
  {
    iso_id: '7.8.1',
    domain: '7. 물리적 통제',
    control_no: '7.8',
    control_name: '장비배치 및 보호',
    check_item: '정보시스템은 환경적, 유해요소, 비인가 접근 등의 위협을 감소시킬 수 있는 장소에 설치 및 운영되고 있습니까?',
    status: '적용',
    operation: 'ㅇ 당사는 AWS 클라우드 인프라 및 코로케이션 서비스를 사용하고 있으며, 해당 시설은 물리적 보호 조치가 적용되어 있음',
    evidence: '- 평촌 IDC 정보',
    policy: '- SG06_물리적보안지침_Ver 2.0   · 제4장 전산실 보호 - SPR04_보호구역 출입절차서_Ver 1.0',
    mapped_isms: [{"req_id": "2.4.4", "subject": "보호설비 운영", "category": "물리 보안"}],
    mapping_confidence: 'direct'
  },
  {
    iso_id: '7.9.1',
    domain: '7. 물리적 통제',
    control_no: '7.9',
    control_name: 'Off-premises의 자산 보호',
    check_item: '장비, 정보, 소프트웨어는 사전 승인 없이 외부로 반출되지 않도록 규정 및 운영 있습니까?',
    status: '적용',
    operation: 'ㅇ 중요단말기 등 안전한 자산 보호를 위한 단말 보안 지침을 수립 및 운영하고 있음',
    evidence: '',
    policy: '- SG06_물리적보안지침_Ver 2.0   · 제4장 전산실 보호 - SG07_단말보안지침_Ver 2.0   · 제3장 단말보안 준수사항   · 제17조(중요단말기 지정 및 관리)',
    mapped_isms: [{"req_id": "2.4.3", "subject": "정보시스템 보호", "category": "물리 보안"}],
    mapping_confidence: 'direct'
  },
  {
    iso_id: '7.10.1',
    domain: '7. 물리적 통제',
    control_no: '7.10',
    control_name: '저장 매체',
    check_item: '이동형 저장 매체의 불법적인 접근, 오남용, 데이터 손상에 대한 보호대책이 수립되어 있습니까?',
    status: '적용',
    operation: 'ㅇ 백신(엑소스피어)를 통해 보조저장매체를 통제하고 있으며 정기적으로 검토하고 있음 ㅇ 단말 보안 지침 등을 통해 보조저장매체를 안전하게 통제하기 위한 규정을 수립 및 운영하고 있음',
    evidence: '',
    policy: '- SG07_단말보안지침_Ver 2.0   · 제12조(보조저장매체 통제)   · 제23조(이전 및 용도 변경)',
    mapped_isms: [{"req_id": "2.1.3", "subject": "정보자산 관리", "category": "인적 보안"}],
    mapping_confidence: 'direct'
  },
  {
    iso_id: '7.10.2',
    domain: '7. 물리적 통제',
    control_no: '7.10',
    control_name: '저장 매체',
    check_item: '더 이상 필요하지 않은 매체는 공식적인 절차를 통해 안전하게 폐기하도록 규정 및 운영하고 있습니까?',
    status: '적용',
    operation: '',
    evidence: '',
    policy: '',
    mapped_isms: [{"req_id": "2.1.3", "subject": "정보자산 관리", "category": "인적 보안"}],
    mapping_confidence: 'direct'
  },
  {
    iso_id: '7.10.3',
    domain: '7. 물리적 통제',
    control_no: '7.10',
    control_name: '저장 매체',
    check_item: '이동형 저장 매체의 이동 중 불법적인 접근, 오남용, 데이터 손상에 대한 보호대책이 수립되어 있습니까?',
    status: '적용',
    operation: '',
    evidence: '',
    policy: '',
    mapped_isms: [{"req_id": "2.1.3", "subject": "정보자산 관리", "category": "인적 보안"}],
    mapping_confidence: 'direct'
  },
  {
    iso_id: '7.10.4',
    domain: '7. 물리적 통제',
    control_no: '7.10',
    control_name: '저장 매체',
    check_item: '장비, 정보, 소프트웨어는 사전에 허가없이 다른 장소로의 이동을 금지하는 규정이 존재하며 이를 이행하고 있습니까?',
    status: '적용',
    operation: '',
    evidence: '',
    policy: '',
    mapped_isms: [{"req_id": "2.1.3", "subject": "정보자산 관리", "category": "인적 보안"}],
    mapping_confidence: 'direct'
  },
  {
    iso_id: '7.11.1',
    domain: '7. 물리적 통제',
    control_no: '7.11',
    control_name: '지원 유틸리티',
    check_item: '전원공급 이상이나 기타 전기관련 사고 발생을 대비한 설비가 구축되어 있으며 관리는 이루어지고 있습니까?',
    status: '적용',
    operation: 'ㅇ 당사는 AWS 클라우드(AWS 서울 리전, 가용영역 다중화) 및 LG U+ 평촌 IDC(코로케이션 서비스)를 이용하고 있으며, 각 시설은 이중 전원 공급, UPS, 비상 발전기, 항온항습기 등의 보조 유틸리티를 운영하고 있음.',
    evidence: '- 평촌 IDC 정보',
    policy: '- SG06_물리적보안지침_Ver 2.0   · 제10조(전원, 공조 등 설비에 관한 사항)   · 제11조(전산실 등에 관한 사항)',
    mapped_isms: [{"req_id": "2.4.1", "subject": "보호구역 지정", "category": "물리 보안"}],
    mapping_confidence: 'direct'
  },
  {
    iso_id: '7.12.1',
    domain: '7. 물리적 통제',
    control_no: '7.12',
    control_name: '케이블링 보호',
    check_item: '데이터와 정보서비스를 지원하는 전력 및 통신 케이블은 차단 및 손상으로부터 보호되고 있습니까?',
    status: '적용',
    operation: 'ㅇ LG U+ 평촌 IDC는 TPS실을 통해 전용 통신케이블이 인입되며, 케이블은 전용 경로로 관리되어 비인가 접근·도청·물리적 손상 위험을 최소화하고 있음',
    evidence: '- 평촌 IDC 정보',
    policy: '- SG06_물리적보안지침_Ver 2.0   · 제10조(전원, 공조 등 설비에 관한 사항)   · 제11조(전산실 등에 관한 사항)',
    mapped_isms: [{"req_id": "2.4.1", "subject": "보호구역 지정", "category": "물리 보안"}],
    mapping_confidence: 'direct'
  },
  {
    iso_id: '7.13.1',
    domain: '7. 물리적 통제',
    control_no: '7.13',
    control_name: '장비 유지 보수',
    check_item: '장비는 지속적인 가용성과 무결성을 보장하기 위하여 유지ㆍ보수 되고 있고, 이에 대한 기록이 있습니까?',
    status: '부분적용',
    operation: 'ㅇ 전산실의 경우 출입통제 및 CCTV 등이 구성되어 있으며, 정기적으로 검토를 수행하고 있음',
    evidence: '- 캡스 로그 백업 설정 화면',
    policy: '- SG08_정보시스템보안지침_Ver 2.0   · 제3장 정보시스템 운영 관리 - SG06_물리적보안지침_Ver 2.0   · 제6장 영상정보처리기기 설치 및 운영 관리',
    mapped_isms: [{"req_id": "2.9.5", "subject": "로그 및 접속기록 점검", "category": "시스템 및 서비스 운영관리"}],
    mapping_confidence: 'partial'
  },
  {
    iso_id: '7.14.1',
    domain: '7. 물리적 통제',
    control_no: '7.14',
    control_name: '장비의 안전한 폐기 또는 재사용',
    check_item: '중요 데이터나 정품 소프트웨어는 장비의 폐기/ 재사용 전에 기록된 내용이 완전히 삭제되어 복구가 불가능한지 확인하고 점검하고 있습니까?',
    status: '적용',
    operation: 'ㅇ 관련 지침을 통해 자산 폐기 등에 대한 규정을 수립하고 있음  ㅇ 규정 지침 개정에 따라 폐기 관리 수행 예정',
    evidence: '',
    policy: '- SG07_단말보안지침_Ver 2.0   · 제23조(이전 및 용도 변경) - SG08_정보시스템보안지침_Ver 2.0   · 제12조(정보시스템 폐기)',
    mapped_isms: [{"req_id": "2.9.5", "subject": "로그 및 접속기록 점검", "category": "시스템 및 서비스 운영관리"}],
    mapping_confidence: 'direct'
  },
  {
    iso_id: '7.14.2',
    domain: '7. 물리적 통제',
    control_no: '7.14',
    control_name: '장비의 안전한 폐기 또는 재사용',
    check_item: '중요한 정보를 담고 있는 저장 매체의 폐기시에는 이를 물리적으로 파기하고 있습니까?',
    status: '적용',
    operation: '',
    evidence: '',
    policy: '',
    mapped_isms: [{"req_id": "2.9.5", "subject": "로그 및 접속기록 점검", "category": "시스템 및 서비스 운영관리"}],
    mapping_confidence: 'direct'
  },
  {
    iso_id: '8.1.1',
    domain: '8. 기술적 통제',
    control_no: '8.1',
    control_name: '사용자 엔드포인트 장치',
    check_item: '업무 목적상 활용되는 모바일 기기 대상 통제 및 사용 정책을 마련하고 있습니까?',
    status: '적용',
    operation: 'ㅇ 당사는 단말 보안지침을 통해 사용자 엔드포인트 장치에 대한 보호에 대한 규정을 수립 및 운영하고 있음',
    evidence: '- 단말기 NAC 인증 화면 - 단말기 백신 프로그램(엑소스피어) - 단말기 취약점 진단 프로그램(엑소스피어)',
    policy: '- SG07_단말보안 지침_Ver 2.0   · 제7조(단말기 보호대책)',
    mapped_isms: [{"req_id": "2.9.4", "subject": "로그 및 접속기록 관리", "category": "시스템 및 서비스 운영관리"}],
    mapping_confidence: 'direct'
  },
  {
    iso_id: '8.1.2',
    domain: '8. 기술적 통제',
    control_no: '8.1',
    control_name: '사용자 엔드포인트 장치',
    check_item: '사용자들에 의해 방치되는 장비가 없도록 적절한 보호방안을 강구하고 있습니까?',
    status: '적용',
    operation: '',
    evidence: '',
    policy: '',
    mapped_isms: [{"req_id": "2.9.4", "subject": "로그 및 접속기록 관리", "category": "시스템 및 서비스 운영관리"}],
    mapping_confidence: 'direct'
  },
  {
    iso_id: '8.2.1',
    domain: '8. 기술적 통제',
    control_no: '8.2',
    control_name: '특수 접근 권한',
    check_item: '특수 권한의 할당 및 사용을 관리하기위한 지침이 수립되어 있으며 정기적으로 검토를 실시하고 있습니까?',
    status: '적용',
    operation: 'ㅇ 계정관리 지침을 통해 특수권한 관리에 대한 규정을 수립 및 운영하고 있음',
    evidence: '',
    policy: '- SG05_계정관리지침_Ver 2.0   · 제7조(계정 관리)',
    mapped_isms: [{"req_id": "2.1.3", "subject": "정보자산 관리", "category": "인적 보안"}],
    mapping_confidence: 'direct'
  },
  {
    iso_id: '8.2.2',
    domain: '8. 기술적 통제',
    control_no: '8.2',
    control_name: '특수 접근 권한',
    check_item: '특수 권한 사용시 이에 대한 로그를 증적으로 남기고 있습니까?',
    status: '적용',
    operation: 'ㅇ 쿼리파이를 통해 서버, 데이터베이스, 쿠버네티스에 대한 사용 이력에 대한 로그를 보유하고 있음',
    evidence: '- 서버 접근통제 솔루션 로그 내역(쿼리파이)',
    policy: '',
    mapped_isms: [{"req_id": "2.1.3", "subject": "정보자산 관리", "category": "인적 보안"}],
    mapping_confidence: 'direct'
  },
  {
    iso_id: '8.3.1',
    domain: '8. 기술적 통제',
    control_no: '8.3',
    control_name: '정보 접근 제한',
    check_item: '정보와 응용 시스템 접근제한 사항을 규정화하고 있으며 구현되어 있습니까?  -사용자 접근이 허가되지 않은 응용프로그램의 기능에 대한 정보제공 제한  -중요한 정보(기밀 정보)를 처리하는 응용프로그램의 출력물 접근통제',
    status: '적용',
    operation: 'ㅇ 계정관리지침을 통해 접근권한 부여, 접근권한 관리에 대한 규정을 수립 및 운영하고 있음 ㅇ 연구개발망, 운영망 등으로 분리하여 시스템에 대한 접근 통제 및 제한을 하고 있음 ㅇ FortiClient 연결 시만 회사 네트워크로 접근이 가능하도록 구성되어 있음',
    evidence: '- 서버 접근제어 구현 화면(쿼리파이) - 네트워크 구성도 - 단말기 NAC 관련 정책 설정 내역',
    policy: '- SG05_계정관리지침_Ver 2.0   · 제10조(접근권한 부여)   · 제11조(접근권한 관리)',
    mapped_isms: [{"req_id": "2.5.4", "subject": "비밀번호 관리", "category": "인증 및 권한관리"}],
    mapping_confidence: 'direct'
  },
  {
    iso_id: '8.4.1',
    domain: '8. 기술적 통제',
    control_no: '8.4',
    control_name: '소스 코드에 대한 접근',
    check_item: '소스 프로그램 접근에 대한 통제절차를 수립하고 관리자는 각 운영시스템 별로 지정되어 있습니까?',
    status: '적용',
    operation: 'ㅇ github를 계정에 따른 접근 통제 적용',
    evidence: '- 정보자산 관리대장',
    policy: '- SG09_응용프로그램보안지침_Ver 2.0   · 제8조(보안 요구사항 분석)   · 제13조(응용프로그램 일반 통제)   · 제17조(접근통제)',
    mapped_isms: [{"req_id": "2.5.4", "subject": "비밀번호 관리", "category": "인증 및 권한관리"}],
    mapping_confidence: 'direct'
  },
  {
    iso_id: '8.5.1',
    domain: '8. 기술적 통제',
    control_no: '8.5',
    control_name: '인증 보호',
    check_item: '운영체제에 대한 안전한 로그온을 보장하기 위하여 사용자 인증절차 등에 의해 통제되고 있습니까?',
    status: '적용',
    operation: 'ㅇ Okta를 통해 사용자 인증을 통제하고 관리하고 있음',
    evidence: '- Okta 로그인 인증 화면',
    policy: '- SG07_단말 보안지침_Ver 2.0   · 제7조(단말기 보호대책)   · 제8조(비밀번호 생성 및 관리)',
    mapped_isms: [{"req_id": "2.5.2", "subject": "사용자 식별", "category": "인증 및 권한관리"}],
    mapping_confidence: 'direct'
  },
  {
    iso_id: '8.6.1',
    domain: '8. 기술적 통제',
    control_no: '8.6',
    control_name: '용량 관리 제어',
    check_item: '용량관리 지침을 마련하고 이에 따라 용량관리를 실시하고 있습니까?  - 사용자 용량 요구사항 - 용량 모니터링 - 용량관리 책임 및 보고 - 추가 자원의 필요성 및 시기에 대한 예상',
    status: '적용',
    operation: 'ㅇ 그라파나(Grafana)를 통해 시스템에 대한 가용성 모니터링을 수행하고 있음',
    evidence: '- 정보시스템 가용성 모니터링 화면(그라파나)',
    policy: '- SG08_정보시스템보안지침_Ver 2.0   · 제19조(성능 및 용량 관리)',
    mapped_isms: [{"req_id": "2.9.4", "subject": "로그 및 접속기록 관리", "category": "시스템 및 서비스 운영관리"}],
    mapping_confidence: 'direct'
  },
  {
    iso_id: '8.7.1',
    domain: '8. 기술적 통제',
    control_no: '8.7',
    control_name: '악성코드 방지',
    check_item: '악성소프트웨어(악성코드, 바이러스 등) 통제를 위한 지침 및 절차가 수립되어 있으며 이행하고 있습니까? -주기적인 점검 및 정기 업데이트 -보안 설정 지침 등',
    status: '적용',
    operation: 'ㅇ 엑소스피어를 통해 악성코드에 대한 보호를 운영하고 있음 ㅇ 악성코드 감염 시 대응 프로세스를 위한 침해사고 대응 매뉴얼을 수립 및 운영하고 있음',
    evidence: '- 단말기 백신 프로그램 설치 화면(엑소스피어)',
    policy: '- SG07_단말보안지침_Ver2.0   · 제13조(악성코드 감염방지) - SG08_정보시스템보안지침_Ver 2.0   · 제25조(백신 설치 및 운영)',
    mapped_isms: [{"req_id": "2.9.3", "subject": "백업 및 복구관리", "category": "시스템 및 서비스 운영관리"}],
    mapping_confidence: 'direct'
  },
  {
    iso_id: '8.8.1',
    domain: '8. 기술적 통제',
    control_no: '8.8',
    control_name: '기술적 취약점 관리',
    check_item: '기술적인 점검에 따라 발견된 취약성에 대해 규정 및 실시하고 있습니까?',
    status: '적용',
    operation: 'ㅇ 위험관리 절차 및 보호대책에 대한 기준을 수립 및 운영하고 있음 ㅇ 매년 웹, 인프라 등 기술 취약점 진단을 수행 및 개선하고 있음',
    evidence: '- 요구사항 6.1 증적 동일(위험관리 계획서/결과서)',
    policy: '- SG11_정보보안점검지침_Ver 2.0   · 제10조(기반시설 보안 취약점 분석·평가)',
    mapped_isms: [{"req_id": "2.7.2", "subject": "암호키 관리", "category": "정보시스템 도입 및 개발 보안"}],
    mapping_confidence: 'direct'
  },
  {
    iso_id: '8.8.2',
    domain: '8. 기술적 통제',
    control_no: '8.8',
    control_name: '기술적 취약점 관리',
    check_item: '정보시스템의 정기적 점검결과로 발견된 취약성에 대해 조치를 취하도록 규정하고 있습니까?',
    status: '적용',
    operation: '',
    evidence: '',
    policy: '',
    mapped_isms: [{"req_id": "2.7.2", "subject": "암호키 관리", "category": "정보시스템 도입 및 개발 보안"}],
    mapping_confidence: 'direct'
  },
  {
    iso_id: '8.9.1',
    domain: '8. 기술적 통제',
    control_no: '8.9',
    control_name: '형상 관리',
    check_item: '형상관리 대상 전반에 대한 관리 번호가 있는 목록 등이 존재하고 문서화하여 식별이 이루어지고 있습니까? - 형상관리 계획서, 품질관리 매뉴얼 - 요구사항 명세서 - 설계/인터페이스 명세서 - 테스트 설계서 - 소스코드',
    status: '적용',
    operation: 'ㅇ 소스코드 형상관리로 git을 사용하고 있음 ㅇ Jira를 통해 정보시스템 변경, 소스 코드 배포 등에 대해 관리하고 있음 ㅇ Argo CD 적용으로 배포 절차 강화 예정',
    evidence: '- 정보자산 관리대장',
    policy: '- SG09_응용프로그램보안지침_Ver 2.0   · 제20조(소스관리)',
    mapped_isms: [{"req_id": "2.9.1", "subject": "변경관리", "category": "시스템 및 서비스 운영관리"}],
    mapping_confidence: 'direct'
  },
  {
    iso_id: '8.9.2',
    domain: '8. 기술적 통제',
    control_no: '8.9',
    control_name: '형상 관리',
    check_item: '형상변경 요청을 검토, 승인 등 정보보호위원회의 승인을 통한 형상 통제가 이루어지고 있습니까?',
    status: '적용',
    operation: '',
    evidence: '',
    policy: '',
    mapped_isms: [{"req_id": "2.9.1", "subject": "변경관리", "category": "시스템 및 서비스 운영관리"}],
    mapping_confidence: 'direct'
  },
  {
    iso_id: '8.9.3',
    domain: '8. 기술적 통제',
    control_no: '8.9',
    control_name: '형상 관리',
    check_item: '조직구성원 및 이해관계자 등에게 형상 변경 사항에 대한 기록 및 보고가 이루어지고 있고, 대상별로 적절한 정보를 제공하고 있습니까? - 승인된 형상 리스트 - 계획한 변경 상태 - 승인 변경 구현 상태',
    status: '적용',
    operation: '',
    evidence: '',
    policy: '',
    mapped_isms: [{"req_id": "2.9.1", "subject": "변경관리", "category": "시스템 및 서비스 운영관리"}],
    mapping_confidence: 'direct'
  },
  {
    iso_id: '8.10.1',
    domain: '8. 기술적 통제',
    control_no: '8.10',
    control_name: '정보 삭제',
    check_item: '정보 시스템, 장치 또는 기타 저장 매체에 저장된 불필요한 정보(개인,중요)에 대하여 삭제가 이루어지고 있습니까?',
    status: '적용',
    operation: 'ㅇ 원칙적으로 민감 및 개인정보 파일의 보유를 금지하고 있으며, 업무 상 필요한 경우 암호화하여 보관하도록 규정하고 있음 ㅇ 백신(엑소스피어)를 통해 개인정보 파일에 대한 탐지 및 유출 내역을 확인하고 있음',
    evidence: '- 개인정보 파일 탐지 및 유출 모니터링 화면(엑소스피어)',
    policy: '- SG12_자산분석 및 위험관리지침_Ver 2.0   · 제7조(자산분석 및 위험관리 절차)',
    mapped_isms: [{"req_id": "2.1.3", "subject": "정보자산 관리", "category": "인적 보안"}],
    mapping_confidence: 'direct'
  },
  {
    iso_id: '8.11.1',
    domain: '8. 기술적 통제',
    control_no: '8.11',
    control_name: '데이터 마스킹',
    check_item: '조직 내에 개인정보 업무처리를 목적으로 개인정보의 조회, 출력 등 업무를 수행하는 과정에서 개인정보가 화면에 노출될 경우 정책에 따라 조치 대상별로 동일하고 일관된 방식으로 정보보호를 위한 마스킹이 이루어지고 있습니까?',
    status: '부분적용',
    operation: 'ㅇ admin 페이지에 대한 개인정보 마스킹을 처리하고 있음(개발 진행 중)',
    evidence: '- admin 페이지 개인정보 마스킹 화면',
    policy: '- SG09_응용프로그램보안지침_Ver 2.0   · 제8조(보안 요구사항 분석)',
    mapped_isms: [{"req_id": "2.5.3", "subject": "사용자 인증", "category": "인증 및 권한관리"}],
    mapping_confidence: 'partial'
  },
  {
    iso_id: '8.12.1',
    domain: '8. 기술적 통제',
    control_no: '8.12',
    control_name: '데이터 유출 방지',
    check_item: '데이터 유출 방지 조치에 관하여 로깅 및 모니터링이 이루어지고 있고, 구성원별 엑세스 권한을 부여하고 있습니까?',
    status: '부분적용',
    operation: 'ㅇ 보조저장매체 통제, 개인정보 탐지 및 유출 내역 백신을 통해 기록 및 정기적으로 검토하고 있음',
    evidence: '- 개인정보 파일 탐지 및 유출 모니터링 화면(엑소스피어)',
    policy: '- SG09_응용프로그램보안지침_Ver 2.0   · 제21조(로그 관리)',
    mapped_isms: [{"req_id": "2.9.5", "subject": "로그 및 접속기록 점검", "category": "시스템 및 서비스 운영관리"}],
    mapping_confidence: 'partial'
  },
  {
    iso_id: '8.12.2',
    domain: '8. 기술적 통제',
    control_no: '8.12',
    control_name: '데이터 유출 방지',
    check_item: '조직의 네트워크 구성에 따른 포인트별 어플리케이션 엑세스 권한 설정, 인터넷 엑세스 설정, 유무선 네트워크에 대한 관리 및 암호화 등 적절한 수준의 조치가 이루어지고 있습니까?',
    status: '적용',
    operation: '',
    evidence: '',
    policy: '',
    mapped_isms: [{"req_id": "2.9.5", "subject": "로그 및 접속기록 점검", "category": "시스템 및 서비스 운영관리"}],
    mapping_confidence: 'direct'
  },
  {
    iso_id: '8.13.1',
    domain: '8. 기술적 통제',
    control_no: '8.13',
    control_name: '정보 백업',
    check_item: '중요 데이터와 운영요소들을 식별하여 데이터 및 장비의 무결성과 가용성을 유지하기 위한 백업계획을 수립하여 이행하고 복구테스트를 실시하고 있습니까?',
    status: '적용',
    operation: 'ㅇ 정기적으로 데이터를 백업 및 관리하고 있음(AWS RDS 백업, AMI 백업 등)',
    evidence: '- RDS 자동 백업 정책 내역 - AMI 백업 내역',
    policy: '- SG08_정보시스템보안지침_Ver 2.0   · 제21조(백업 관리)',
    mapped_isms: [{"req_id": "2.12.1", "subject": "재해∙재난 대비 안전조치", "category": "재해복구"}],
    mapping_confidence: 'direct'
  },
  {
    iso_id: '8.14.1',
    domain: '8. 기술적 통제',
    control_no: '8.14',
    control_name: '정보처리설비의 이중화',
    check_item: '정보처리 시설은 가용성을 보장해줄수 있는 보안 지침 및 대책을 수립하고 이중화하여 운영하고 있습니까?',
    status: '적용',
    operation: 'ㅇ EKS로 구성되어 있으며, 기본적으로 다수의 가용 리전을 사용하고 있음',
    evidence: '- 네트워크 구성도',
    policy: '- SG08_정보시스템보안지침_Ver 2.0   · 제23조(이중화 구성)',
    mapped_isms: [{"req_id": "2.12.2", "subject": "재해 복구 시험 및 개선", "category": "재해복구"}],
    mapping_confidence: 'direct'
  },
  {
    iso_id: '8.15.1',
    domain: '8. 기술적 통제',
    control_no: '8.15',
    control_name: '로깅',
    check_item: '사용자 활동, 예외, 고장, 정보보호 이벤트를 기록하는 이벤트 로그를 생성하고 보존하며 주기적으로 백업 및 검토하고 있습니까?',
    status: '부분적용',
    operation: 'ㅇ 쿼리파이를 통해 DB, 서버, 쿠버네티스에 대한 사용자 활동 및 이벤트에 대한 로그를 기록 및 검토하고 있음 ㅇ 관리자페이지에 대한 이벤트에 대한 로그를 기록 및 검토하고 있음 - 각 로그에 대한 정기적인 모니터링 예정',
    evidence: '- 서버 접근통제 솔루션 로그 내역(쿼리파이)',
    policy: '- SG09_응용프로그램보안지침_Ver 2.0   · 제21조(로그 관리) - SG08_정보시스템보안지침_Ver 2.0   · 제16조(로그관리)   · 제17조(로그 분석 및 모니터링)',
    mapped_isms: [{"req_id": "2.9.7", "subject": "정보자산의 재사용 및 폐기", "category": "시스템 및 서비스 보안관리"}],
    mapping_confidence: 'partial'
  },
  {
    iso_id: '8.15.2',
    domain: '8. 기술적 통제',
    control_no: '8.15',
    control_name: '로깅',
    check_item: '로그 관리 시스템과 로그정보는 무단 변조 및 접근제한, 로깅범위, 책임과 로그의 백업 등을 포함한 로그관리 지침이 정의되어 있습니까?',
    status: '적용',
    operation: '',
    evidence: '',
    policy: '',
    mapped_isms: [{"req_id": "2.9.7", "subject": "정보자산의 재사용 및 폐기", "category": "시스템 및 서비스 보안관리"}],
    mapping_confidence: 'direct'
  },
  {
    iso_id: '8.15.3',
    domain: '8. 기술적 통제',
    control_no: '8.15',
    control_name: '로깅',
    check_item: '시스템 관리자와 시스템 운영자의 활동을 주기적으로 검토하고 있습니까?',
    status: '부분적용',
    operation: '',
    evidence: '',
    policy: '',
    mapped_isms: [{"req_id": "2.9.7", "subject": "정보자산의 재사용 및 폐기", "category": "시스템 및 서비스 보안관리"}],
    mapping_confidence: 'partial'
  },
  {
    iso_id: '8.16.1',
    domain: '8. 기술적 통제',
    control_no: '8.16',
    control_name: '모니터링 활동',
    check_item: '내·외부에 의한 침해시도, 개인정보유출 시도, 부정행위 등 이상행위를 탐지할 수 있도록 주요 정보시스템, 응용프로그램, 네트워크, 보안시스템 등에서 발생한 네트워크 트래픽, 데이터 흐름, 이벤트 로그 등을 수집하여 분석 및 모니터링하고 있습니까?',
    status: '적용',
    operation: 'ㅇ 애플리케이션 침해 시도에 대해 WAF를 구성하여 보안 관제를 수행하고 있음',
    evidence: '- 보안관제 보고서(싸이버원)',
    policy: '- SG09_응용프로그램보안지침_Ver 2.0   · 제21조(로그 관리) - SG08_정보시스템보안지침_Ver 2.0   · 제16조(로그관리)   · 제17조(로그 분석 및 모니터링)   · 제18조(침해시도 모니터링)',
    mapped_isms: [{"req_id": "2.9.7", "subject": "정보자산의 재사용 및 폐기", "category": "시스템 및 서비스 보안관리"}],
    mapping_confidence: 'direct'
  },
  {
    iso_id: '8.16.2',
    domain: '8. 기술적 통제',
    control_no: '8.16',
    control_name: '모니터링 활동',
    check_item: '침해시도, 개인정보유출시도, 부정행위 등의 여부를 판단하기 위한 기준을 정의하고 이`에 따라 이상행위의 판단 및 조사 등 후속 조치가 적시에 이루어지고 있습니까?',
    status: '적용',
    operation: '',
    evidence: '',
    policy: '',
    mapped_isms: [{"req_id": "2.9.7", "subject": "정보자산의 재사용 및 폐기", "category": "시스템 및 서비스 보안관리"}],
    mapping_confidence: 'direct'
  },
  {
    iso_id: '8.17.1',
    domain: '8. 기술적 통제',
    control_no: '8.17',
    control_name: '시각 동기화',
    check_item: '다음 사항을 위해 시스템 시각을 정확히 설정하고 있습니까? - 감사기록의 명확성 보장 - 법적인 자료나 징계 자료로서의 효력 발생',
    status: '적용',
    operation: 'ㅇ 각 서버에 대한 NTP를 설정하여 운영하고 있음',
    evidence: '- NTP 설정화면',
    policy: '- SG08_정보시스템보안지침_Ver 2.0   · 제13조(시각동기화)',
    mapped_isms: [{"req_id": "2.9.1", "subject": "변경관리", "category": "시스템 및 서비스 운영관리"}],
    mapping_confidence: 'direct'
  },
  {
    iso_id: '8.18.1',
    domain: '8. 기술적 통제',
    control_no: '8.18',
    control_name: '권한 있는 유틸리티 프로그램 사용',
    check_item: '운영시스템에 허가되지 않은 유틸리티 프로그램의 사용을 제한하며 통제되고 있습니까?',
    status: '적용',
    operation: 'ㅇ 운영 시스템 배포 시 허용한 유틸리티 프로그램만 배포되어 통제 되고 있음',
    evidence: '',
    policy: '- SG08_정보시스템보안지침_Ver 2.0   · 제35조(정보보호시스템 운영)',
    mapped_isms: [{"req_id": "2.9.4", "subject": "로그 및 접속기록 관리", "category": "시스템 및 서비스 운영관리"}],
    mapping_confidence: 'direct'
  },
  {
    iso_id: '8.19.1',
    domain: '8. 기술적 통제',
    control_no: '8.19',
    control_name: '운영 체제에 소프트 웨어 설치',
    check_item: '업무망에 접속하는 모든 PC는 회사가 정한 필수 보안 프로그램을 설치 및 운영하고 있습니까?',
    status: '적용',
    operation: 'ㅇ 당사는 FortiClient를 통해 필수 보안 프로그램인 엑소스피어(백신), FortiClient, MDM을 설치하여야만 업무망 접속이 가능하도록 구성되어 있음',
    evidence: '- 단말기 백신 프로그램(엑소스피어) - Okta 로그인 인증화면',
    policy: '- SG07_단말 보안지침_Ver 2.0   · 제14조(비인가 소프트웨어 통제) - SG08_정보시스템보안지침_Ver 2.0   · 제35조(정보보호시스템 운영)',
    mapped_isms: [{"req_id": "2.9.2", "subject": "성능 및 장애관리", "category": "시스템 및 서비스 운영관리"}],
    mapping_confidence: 'direct'
  },
  {
    iso_id: '8.19.2',
    domain: '8. 기술적 통제',
    control_no: '8.19',
    control_name: '운영 체제에 소프트 웨어 설치',
    check_item: '임직원 및 외주인력 등 단말기내 허가되지 않은 유틸리티 프로그램의 사용을 제한하며 통제되고 있습니까?',
    status: '적용',
    operation: '',
    evidence: '',
    policy: '',
    mapped_isms: [{"req_id": "2.9.2", "subject": "성능 및 장애관리", "category": "시스템 및 서비스 운영관리"}],
    mapping_confidence: 'direct'
  },
  {
    iso_id: '8.20.1',
    domain: '8. 기술적 통제',
    control_no: '8.20',
    control_name: '네트워크 보호',
    check_item: '공유 네트워크 및 공유 시스템 자원이 제공되는 경우 네트워크에 연결하는 사용자들의 권한이 접근통제 정책과 업무 어플리케이션의 요구사항에 따라 제한되고 있습니까?',
    status: '적용',
    operation: 'ㅇ 당사는 NAC(FortiClient)을 통해 인가된 안전한 엔드포인트만 내부 네트워크에 접근할 수 있도록 구성되어 있음',
    evidence: '- 단말기 NAC 관련 정책 설정 내역 - 네트워크 구성도',
    policy: '- SG07_단말 보안지침_Ver 2.0   · 제10조(공유 폴더 및 파일 공유)',
    mapped_isms: [{"req_id": "2.7.2", "subject": "암호키 관리", "category": "정보시스템 도입 및 개발 보안"}],
    mapping_confidence: 'direct'
  },
  {
    iso_id: '8.21.1',
    domain: '8. 기술적 통제',
    control_no: '8.21',
    control_name: '네트워크 서비스의 보호',
    check_item: '사용자에게 허가된 서비스만 접근이 가능하도록 네트워크 접근 정책이 수립되어 있으며 이행하고 있습니까?',
    status: '적용',
    operation: 'ㅇ 당사는 게스트망, 연구개발망, 업무망/운영망 으로 분리하여 네트워크 분리 및 접근 정책이 수립 및 운영되어 있음',
    evidence: '- 단말기 NAC 관련 정책 설정 내역 - 네트워크 구성도',
    policy: '- SG07_단말 보안지침_Ver 2.0   · 제15조(인터넷 접속통제)',
    mapped_isms: [{"req_id": "2.9.4", "subject": "로그 및 접속기록 관리", "category": "시스템 및 서비스 운영관리"}],
    mapping_confidence: 'direct'
  },
  {
    iso_id: '8.22.1',
    domain: '8. 기술적 통제',
    control_no: '8.22',
    control_name: '네트워크 분리',
    check_item: '정보서비스, 사용자, 정보시스템 등의 그룹들이 네트워크상에서 서로 분리되어 있습니까?',
    status: '적용',
    operation: 'ㅇ 당사는 게스트망, 연구개발망, 업무망/운영망 으로 분리하여 네트워크 분리 및 접근 정책이 수립 및 운영되어 있음',
    evidence: '- 네트워크 구성도',
    policy: '- SG08_정보시스템보안지침_Ver 2.0   · 제14조(정보시스템 접근통제)   · 제28조(네트워크 구성 관리)',
    mapped_isms: [{"req_id": "2.7.1", "subject": "암호정책 적용", "category": "암호화 적용"}],
    mapping_confidence: 'direct'
  },
  {
    iso_id: '8.23.1',
    domain: '8. 기술적 통제',
    control_no: '8.23',
    control_name: '웹 필터링',
    check_item: '악성코드 감염 및 내부정보의 유출 방지를 위해 보안에 취약한 비업무용 웹사이트 접속 및 프로그램 사용을 통제하고 있습니까?',
    status: '적용',
    operation: 'ㅇ 백신(엑소스피어)를 통해 P2P 등 비인가 웹사이트에 대한 접속을 차단 및 운영하고 있음.',
    evidence: '- 네트워크 구성도 - 단말기 NAC 관련 정책 설정 내역 - 비인가 웹사이트 접속 차단 정책(엑소스피어)',
    policy: '- SG07_단말 보안지침_Ver 2.0   · 제15조(인터넷 접속통제)',
    mapped_isms: [{"req_id": "2.7.1", "subject": "암호정책 적용", "category": "암호화 적용"}],
    mapping_confidence: 'direct'
  },
  {
    iso_id: '8.24.1',
    domain: '8. 기술적 통제',
    control_no: '8.24',
    control_name: '암호 사용',
    check_item: '다음의 내용을 포함하는 암호사용에 대한 정책 및 지침이 마련되어 있습니까? - 암호사용 정보의 일반원칙 - 암호사용 운영방침 - 키복구 등 키관리 방법 - 암호정책의 책임 및 역할 - 암호화 수준 결정방법 - 효과적 이행 위해 채택할 표준',
    status: '적용',
    operation: 'ㅇ 안전한 암호화를 위한 암호화 지침을 수립 및 운영하고 있음',
    evidence: '',
    policy: '- SG10_암호화 지침_Ver 2.0   · 제6조(암호화 대상 및 방식)   · 제7조(암호화 방식과 알고리즘 강도)',
    mapped_isms: [{"req_id": "2.6.1", "subject": "네트워크 접근", "category": "접근통제"}],
    mapping_confidence: 'direct'
  },
  {
    iso_id: '8.24.2',
    domain: '8. 기술적 통제',
    control_no: '8.24',
    control_name: '암호 사용',
    check_item: '암호사용시 적절한 암호 알고리즘의 유형, 신뢰성 및 키 길이를 결정하십니까?(혹은 법적요구사항 상급기관의 요구에 부응하는 암호화 알고리즘의 유형, 신뢰성 및 키 길이를 결정하고 있습니까?)',
    status: '적용',
    operation: '',
    evidence: '',
    policy: '',
    mapped_isms: [{"req_id": "2.6.1", "subject": "네트워크 접근", "category": "접근통제"}],
    mapping_confidence: 'direct'
  },
  {
    iso_id: '8.24.3',
    domain: '8. 기술적 통제',
    control_no: '8.24',
    control_name: '암호 사용',
    check_item: '암호 키에 대한 관리지침, 절차 및 방법을 마련하고 있으며 이행하고 있습니까?',
    status: '적용',
    operation: '',
    evidence: '',
    policy: '',
    mapped_isms: [{"req_id": "2.6.1", "subject": "네트워크 접근", "category": "접근통제"}],
    mapping_confidence: 'direct'
  },
  {
    iso_id: '8.25.1',
    domain: '8. 기술적 통제',
    control_no: '8.25',
    control_name: '안전한 개발 라이프 사이클',
    check_item: '정보시스템 개발 시 안전한 개발 프레임워크 개발 절차를 수립하고 이행하고 있습니까?',
    status: '적용',
    operation: 'ㅇ 개발 및 운영 간 환경을 구분하여 관리하고 있으며, 안전한 개발을 위해 응용프로그램 보안지침을 수립 및 운영하고 있음',
    evidence: '',
    policy: '- SG09_응용프로그램보안지침_Ver 2.0   · 제8조(보안 요구사항 분석)',
    mapped_isms: [{"req_id": "2.8.1", "subject": "보안 요구사항 정의", "category": "정보시스템 도입 및 개발 보안"}],
    mapping_confidence: 'direct'
  },
  {
    iso_id: '8.26.1',
    domain: '8. 기술적 통제',
    control_no: '8.26',
    control_name: '애플리케이션 보호 요구사항',
    check_item: '공개서버(Web, Mail, DNS 등)의 보안 관리 정책이 존재하며 외부로 서비스되는 정보의 무결성을 보장하는 방안이 존재합니까? - 공개 서버 내 정보 수집, 저장 및 공개에 대한 허가 및 게시 절차 - 공개 서버의 물리적, 논리적 보안대책',
    status: '적용',
    operation: 'ㅇ 신규 서비스 개발 및 개선 시 보안요구사항을 정의하고, 정기적으로 취약점 평가를 통해 식별 및 관리하고 있음',
    evidence: '- 요구사항 6.1 증적 동일(위험관리 계획서/결과서)',
    policy: '- SG09_응용프로그램보안지침_Ver 2.0   · 제8조(보안 요구사항 분석)   · 제12조(이관 단계)   · 제22조(패키지 프로그램 도입)',
    mapped_isms: [{"req_id": "2.8.3", "subject": "시험과 운영 환경 분리", "category": "정보시스템 도입 및 개발 보안"}],
    mapping_confidence: 'direct'
  },
  {
    iso_id: '8.26.2',
    domain: '8. 기술적 통제',
    control_no: '8.26',
    control_name: '애플리케이션 보호 요구사항',
    check_item: '응용 서비스 거래 시 준용이 필요한 보안통제 사항을 별도 규정으로 문서화하고 있습니까',
    status: '적용',
    operation: '',
    evidence: '',
    policy: '',
    mapped_isms: [{"req_id": "2.8.3", "subject": "시험과 운영 환경 분리", "category": "정보시스템 도입 및 개발 보안"}],
    mapping_confidence: 'direct'
  },
  {
    iso_id: '8.27.1',
    domain: '8. 기술적 통제',
    control_no: '8.27',
    control_name: '보안 시스템 아키텍처 및 엔지니어링 원칙',
    check_item: '시스템 보안을 위한 원칙 및 절차에 따라 정보시스템을 구현하고 문서화하여 이행하고 있습니까?',
    status: '적용',
    operation: 'ㅇ 안전한 시스템 보안 및 개발을 위한 정보시스템 보안 지침, 응용프로그램 보안지침을 수립 및 운영하고 있음',
    evidence: '',
    policy: '- SG08_정보시스템보안지침_Ver 2.0   · 제8조(정보시스템 변경) - SG09_응용프로그램 보안지침_Ver 2.0   · 제8조(보안 요구사항 분석)',
    mapped_isms: [{"req_id": "2.8.2", "subject": "보안 요구사항 검토 및 시험", "category": "정보시스템 도입 및 개발 보안"}],
    mapping_confidence: 'direct'
  },
  {
    iso_id: '8.28.1',
    domain: '8. 기술적 통제',
    control_no: '8.28',
    control_name: '시큐어 코딩',
    check_item: '새로운 정보시스템의 도입이나 기존에 운영 중인 정보시스템의 중대한 변경시 잠재적인 정보보안 취약성을 줄이기 위해 시큐어 코딩 개발 보안 규칙을 적용하고 있습니까?',
    status: '적용',
    operation: 'ㅇ 소나큐브(SonarQube) 및 트리비(Trivy)를 통해 소스코드 및 이미지 취약점 진단을 위한 프로세스를 구성 예정',
    evidence: '- 소스코드 취약점 진단 구축 계획서',
    policy: '- SG09_응용프로그램보안지침_Ver 2.0   · 제8조(보안 요구사항 분석)',
    mapped_isms: [{"req_id": "2.8.4", "subject": "시험 데이터 보안", "category": "정보시스템 도입 및 개발 보안"}],
    mapping_confidence: 'direct'
  },
  {
    iso_id: '8.28.2',
    domain: '8. 기술적 통제',
    control_no: '8.28',
    control_name: '시큐어 코딩',
    check_item: '새로운 정보시스템의 도입이나 기존에 운영 중인 정보시스템의 중대한 변경시 분석ㆍ설계 단계에서 개인정보보호 및 보안측면에서 요구사항을 명확히 정의하여 설계에 반영하고 있습니까?',
    status: '적용',
    operation: '',
    evidence: '',
    policy: '',
    mapped_isms: [{"req_id": "2.8.4", "subject": "시험 데이터 보안", "category": "정보시스템 도입 및 개발 보안"}],
    mapping_confidence: 'direct'
  },
  {
    iso_id: '8.28.3',
    domain: '8. 기술적 통제',
    control_no: '8.28',
    control_name: '시큐어 코딩',
    check_item: '시큐어코딩 개발 보안 교육을 실시하고 있습니까?',
    status: '부분적용',
    operation: '',
    evidence: '',
    policy: '',
    mapped_isms: [{"req_id": "2.8.4", "subject": "시험 데이터 보안", "category": "정보시스템 도입 및 개발 보안"}],
    mapping_confidence: 'partial'
  },
  {
    iso_id: '8.29.1',
    domain: '8. 기술적 통제',
    control_no: '8.29',
    control_name: '개발 및 승인 시 보호 테스트',
    check_item: '개발 기간 중 관련 법령 및 가이드를 준수하여 개발하고 테스트 단계에서 SW보안약점진단을 수행하고 있습니까?',
    status: '적용',
    operation: 'ㅇ 소나큐브(SonarQube) 및 트리비(Trivy)를 통해 소스코드 및 이미지 취약점 진단을 위한 프로세스를 구성 예정',
    evidence: '- 소스코드 취약점 진단 구축 계획서',
    policy: '- SG09_응용프로그램보안지침_Ver 2.0   · 제8조(보안 요구사항 분석)   · 제10조(구현 단계)   · 제11조(테스트 단계)   · 제12조(이관 단계)',
    mapped_isms: [{"req_id": "2.8.5", "subject": "소스 프로그램 관리", "category": "정보시스템 도입 및 개발 보안"}],
    mapping_confidence: 'direct'
  },
  {
    iso_id: '8.29.2',
    domain: '8. 기술적 통제',
    control_no: '8.29',
    control_name: '개발 및 승인 시 보호 테스트',
    check_item: '시스템 도입 및 업그레이드시의 이관기준에 따른 테스트가 수행된 후 이관하고 있습니까?',
    status: '적용',
    operation: '',
    evidence: '',
    policy: '',
    mapped_isms: [{"req_id": "2.8.5", "subject": "소스 프로그램 관리", "category": "정보시스템 도입 및 개발 보안"}],
    mapping_confidence: 'direct'
  },
  {
    iso_id: '8.30.1',
    domain: '8. 기술적 통제',
    control_no: '8.30',
    control_name: '아웃소싱 개발',
    check_item: '소프트웨어 아웃소싱 개발시 보안관리를 위해 정기적인 감독 및 모니터하고 있습니까?',
    status: '적용',
    operation: 'ㅇ 소프트웨어에 대한 아웃소싱을 수행하고 있지 않음',
    evidence: '',
    policy: '- SG09_응용프로그램보안지침_Ver 2.0   · 제16조(외부자 개발보안) - SG04_외부주문보안지침_Ver 2.0   · 제6조(외부주문 계약 준비 준수사항)',
    mapped_isms: [{"req_id": "2.3.3", "subject": "외부자 보안 이행 관리", "category": "외부자 보안"}],
    mapping_confidence: 'direct'
  },
  {
    iso_id: '8.31.1',
    domain: '8. 기술적 통제',
    control_no: '8.31',
    control_name: '개발, 테스트 및 운영 환경의 분리',
    check_item: '개발과 운영환경을 분리하기 위해 운영 지침이 마련되어 있으며 실제 환경이 분리되어 있습니까? 1. 개발,테스트,운영환경 분리 2. 개발에서 운영환경으로의 이전 원칙 정의 3. 운영, 테스트, 개발시 서로 다른 로그온절차(패스워드, 인증화면) 사용하도록 정의',
    status: '적용',
    operation: 'ㅇ AWS 계정 분리를 통해 개발 및 운영 환경을 분리하여 관리 및 운영하고 있음',
    evidence: '- 네트워크 구성도',
    policy: '- SG09_응용프로그램보안지침_Ver 2.0   · 제20조(소스 관리)',
    mapped_isms: [{"req_id": "2.9.1", "subject": "변경관리", "category": "시스템 및 서비스 운영관리"}],
    mapping_confidence: 'direct'
  },
  {
    iso_id: '8.31.2',
    domain: '8. 기술적 통제',
    control_no: '8.31',
    control_name: '개발, 테스트 및 운영 환경의 분리',
    check_item: '조직은 시스템의 전체 개발 생명주기를 포괄하는 시스템 개발 및 통합을 위해 안전한 개발 환경을 수립하고 있습니까?',
    status: '적용',
    operation: '',
    evidence: '',
    policy: '',
    mapped_isms: [{"req_id": "2.9.1", "subject": "변경관리", "category": "시스템 및 서비스 운영관리"}],
    mapping_confidence: 'direct'
  },
  {
    iso_id: '8.32.1',
    domain: '8. 기술적 통제',
    control_no: '8.32',
    control_name: '변경 관리',
    check_item: '정보시스템 관련 자산들의 모든 변경사항을 반영할 수 있는 공식적인 관리절차와 책임을 설정하고 있는가?',
    status: '적용',
    operation: 'ㅇ 정보시스템 보안 지침을 통해 정보시스템 변경에 대한 이력을 관리 ㅇ Jira를 통해 정보시스템 변경에 대한 이력을 관리하고 있음',
    evidence: '- 정보시스템 변경에 대한 관리 내역',
    policy: '- SG08_정보시스템보안지침_Ver 2.0   · 제8조(정보시스템 변경)',
    mapped_isms: [{"req_id": "2.9.1", "subject": "변경관리", "category": "시스템 및 서비스 운영관리"}],
    mapping_confidence: 'direct'
  },
  {
    iso_id: '8.32.2',
    domain: '8. 기술적 통제',
    control_no: '8.32',
    control_name: '변경 관리',
    check_item: '정보시스템의 파괴와 손상을 최소화하기 위하여 공식적인 변경 통제 절차를 수립하고 이행하고 있습니까?',
    status: '적용',
    operation: '',
    evidence: '',
    policy: '',
    mapped_isms: [{"req_id": "2.9.1", "subject": "변경관리", "category": "시스템 및 서비스 운영관리"}],
    mapping_confidence: 'direct'
  },
  {
    iso_id: '8.32.3',
    domain: '8. 기술적 통제',
    control_no: '8.32',
    control_name: '변경 관리',
    check_item: '운영체제 변경이 필요한 경우 응용시스템의 운영이나 보안에 미치는 영향을 분석, 검토 및 테스트를 수행후 변경하도록 변경관리 절차에 명시되어 있습니까?',
    status: '적용',
    operation: '',
    evidence: '',
    policy: '',
    mapped_isms: [{"req_id": "2.9.1", "subject": "변경관리", "category": "시스템 및 서비스 운영관리"}],
    mapping_confidence: 'direct'
  },
  {
    iso_id: '8.32.4',
    domain: '8. 기술적 통제',
    control_no: '8.32',
    control_name: '변경 관리',
    check_item: '소프트웨어 및 패키지의 수정시 원본자료는 보관하고 복사본을 이용하며 변경전 사전 승인을 받고, 공급자의 동의를 얻으며 변경된 내용은 문서화하여 관리하고 있습니까? 또한 변경후 충분한 테스트를 수행한후 운영시스템에 적용하고 있습니까?',
    status: '적용',
    operation: '',
    evidence: '',
    policy: '',
    mapped_isms: [{"req_id": "2.9.1", "subject": "변경관리", "category": "시스템 및 서비스 운영관리"}],
    mapping_confidence: 'direct'
  },
  {
    iso_id: '8.33.1',
    domain: '8. 기술적 통제',
    control_no: '8.33',
    control_name: '테스트 정보',
    check_item: '시험 데이터는 운영데이터에 준하여 보호하고 통제되고, 운영환경에 적용되는 접근통제가 시험환경에도 적용되고 있습니까?',
    status: '적용',
    operation: 'ㅇ 테스트 데이터에 대한 보안 규정을 수립 및 운영하고 있음(응용프로그램 보안 지침) ㅇ 운영데이터는 시험 데이터에 사용하고 있지 않음 ㅇ 매년 위험평가를 수행하고 위험평가 결과에 따른 이행 조치를 수행하고 지속적인 개선을 수행하고 있음',
    evidence: '- 정보보호 규정 및 지침 결재 내역 - 요구사항 6.1 증적 동일(위험관리 계획서/결과서)',
    policy: '- SG09_응용프로그램보안지침_Ver 2.0   · 제19조(테스트 데이터 관리)',
    mapped_isms: [{"req_id": "2.8.5", "subject": "소스 프로그램 관리", "category": "정보시스템 도입 및 개발 보안"}],
    mapping_confidence: 'direct'
  },
  {
    iso_id: '8.34.1',
    domain: '8. 기술적 통제',
    control_no: '8.34',
    control_name: '감사 테스트 중 정보시스템 보호',
    check_item: '정보보안정책의 시행여부를 확인하기위하여 정기적으로 보안감사를 실시하고 있습니까?',
    status: '적용',
    operation: 'ㅇ 정보보안 정책의 시행여부 확인을 위한 보안 감사 수행함',
    evidence: '- 감사 계획서 및 결과서',
    policy: '- SG11_정보보안점검지침_Ver 2.0   · 제 5장 정보보안 내부감사',
    mapped_isms: [{"req_id": "2.11.1", "subject": "사고 예방 및 대응체계 구축", "category": "사고 예방 및 대응"}],
    mapping_confidence: 'direct'
  },
  {
    iso_id: '8.34.2',
    domain: '8. 기술적 통제',
    control_no: '8.34',
    control_name: '감사 테스트 중 정보시스템 보호',
    check_item: '감사 지적 사항에 대한 조치 및 이행 여부를 사후관리 하고 있습니까? (보안감사 결과 조치 확인 및 Feedback 방안의 적정성 확인)',
    status: '적용',
    operation: 'ㅇ 2025년 첫 감사를 수행하였으며 조치 및 이행여부를 관리할 예정',
    evidence: '',
    policy: '',
    mapped_isms: [{"req_id": "2.11.1", "subject": "사고 예방 및 대응체계 구축", "category": "사고 예방 및 대응"}],
    mapping_confidence: 'direct'
  },
];

export const ismsGapItems: ISMSGapItem[] = [
  {
    req_id: '1.1.1',
    category: '관리체계 기반 마련',
    subject: '경영진의 참여',
    detail: '최고경영자는 정보보호 및 개인정보보호 관리체계의 수립과 운영활동 전반에 경영진의 참여가 이루어질 수 있도록 보고 및 의사결정 체계를 수립하여 운영하여야 한다.',
    compliance_cycle: '연간'
  },
  {
    req_id: '1.1.5',
    category: '관리체계 기반 마련',
    subject: '정책 수립',
    detail: '정보보호와 개인정보보호 정책 및 시행문서를 수립∙작성하며, 이때 조직의 정보보호와 개인정보보호 방침 및 방향을 명확하게 제시하여야 한다. 또한 정책과 시행문서는 경영진 승인을 받고, 임직원 및 관련자에게 이해하기 쉬운 형태로 전달하여야 한다.',
    compliance_cycle: '연간'
  },
  {
    req_id: '1.1.6',
    category: '위험 관리',
    subject: '자원 할당',
    detail: '최고경영자는 정보보호와 개인정보보호 분야별 전문성을 갖춘 인력을 확보하고, 관리체계의 효과적 구현과 지속적 운영을 위한 예산 및 자원을 할당하여야 한다.',
    compliance_cycle: '연간'
  },
  {
    req_id: '1.2.1',
    category: '위험 관리',
    subject: '정보자산 식별',
    detail: '조직의 업무특성에 따라 정보자산 분류기준을 수립하여 관리체계 범위 내 모든 정보자산을 식별∙분류하고, 중요도를 산정한 후 그 목록을 최신으로 관리하여야 한다.',
    compliance_cycle: '연간'
  },
  {
    req_id: '1.2.2',
    category: '위험 관리',
    subject: '현황 및 흐름분석',
    detail: '관리체계 전 영역에 대한 정보서비스 및 개인정보 처리 현황을 분석하고 업무 절차와 흐름을 파악하여 문서화하며, 이를 주기적으로 검토하여 최신성을 유지하여야 한다.',
    compliance_cycle: '연간'
  },
  {
    req_id: '1.2.3',
    category: '위험 관리',
    subject: '위험 평가',
    detail: '조직의 대내외 환경분석을 통해 유형별 위협정보를 수집하고 조직에 적합한 위험 평가 방법을 선정하여 관리체계 전 영역에 대하여 연 1회 이상 위험을 평가하며, 수용할 수 있는 위험은 경영진의 승인을 받아 관리하여야 한다.',
    compliance_cycle: '연간'
  },
  {
    req_id: '1.2.4',
    category: '관리체계 운영',
    subject: '보호대책 선정',
    detail: '위험 평가 결과에 따라 식별된 위험을 처리하기 위하여 조직에 적합한 보호대책을 선정하고, 보호대책의 우선순위와 일정∙담당자∙예산 등을 포함한 이행계획을 수립하여 경영진의 승인을 받아야 한다.',
    compliance_cycle: '연간'
  },
  {
    req_id: '1.3.1',
    category: '관리체계 운영',
    subject: '보호대책 구현',
    detail: '선정한 보호대책은 이행계획에 따라 효과적으로 구현하고, 경영진은 이행결과의 정확성과 효과성 여부를 확인하여야 한다.',
    compliance_cycle: '연간'
  },
  {
    req_id: '1.3.2',
    category: '관리체계 운영',
    subject: '보호대책 공유',
    detail: '보호대책의 실제 운영 또는 시행할 부서 및 담당자를 파악하여 관련 내용을 공유하고 교육하여 지속적으로 운영되도록 하여야 한다.',
    compliance_cycle: '연간'
  },
  {
    req_id: '1.3.3',
    category: '관리체계 점검 및 개선',
    subject: '운영현황 관리',
    detail: '조직이 수립한 관리체계에 따라 상시적 또는 주기적으로 수행하여야 하는 운영활동 및 수행 내역은 식별 및 추적이 가능하도록 기록하여 관리하고, 경영진은 주기적으로 운영활동의 효과성을 확인하여 관리하여야 한다.',
    compliance_cycle: '연간'
  },
  {
    req_id: '1.4.2',
    category: '관리체계 점검 및 개선',
    subject: '관리체계 점검',
    detail: '관리체계가 내부 정책 및 법적 요구사항에 따라 효과적으로 운영되고 있는지 독립성과 전문성이 확보된 인력을 구성하여 연 1회 이상 점검하고, 발견된 문제점을 경영진에게 보고하여야 한다.',
    compliance_cycle: '연간'
  },
  {
    req_id: '1.4.3',
    category: '관리체계 점검 및 개선',
    subject: '관리체계 개선',
    detail: '법적 요구사항 준수검토 및 관리체계 점검을 통해 식별된 관리체계상의 문제점에 대한 원인을 분석하고 재발방지 대책을 수립∙이행하여야 하며, 경영진은 개선 결과의 정확성과 효과성 여부를 확인하여야 한다.',
    compliance_cycle: '연간'
  },
  {
    req_id: '2.2.2',
    category: '인적 보안',
    subject: '직무 분리',
    detail: '권한 오∙남용 등으로 인한 잠재적인 피해 예방을 위하여 직무 분리 기준을 수립하고 적용하여야 한다. 다만 불가피하게 직무 분리가 어려운 경우 별도의 보완대책을 마련하여 이행하여야 한다.',
    compliance_cycle: '연간'
  },
  {
    req_id: '2.2.4',
    category: '인적 보안',
    subject: '인식제고 및 교육훈련',
    detail: '임직원 및 관련 외부자가 조직의 관리체계와 정책을 이해하고 직무별 전문성을 확보할 수 있도록 연간 인식제고 활동 및 교육훈련 계획을 수립∙운영하고, 그 결과에 따른 효과성을 평가하여 다음 계획에 반영하여야 한다.',
    compliance_cycle: '연간'
  },
  {
    req_id: '2.2.5',
    category: '인적 보안',
    subject: '퇴직 및 직무변경 관리',
    detail: '퇴직 및 직무변경 시 인사∙정보보호∙개인정보보호∙IT 등 관련 부서별 이행하여야 할 자산반납, 계정 및 접근권한 회수∙조정, 결과확인 등의 절차를 수립∙관리하여야 한다.',
    compliance_cycle: '연간'
  },
  {
    req_id: '2.2.6',
    category: '외부자 보안',
    subject: '보안 위반 시 조치',
    detail: '임직원 및 관련 외부자가 법령, 규제 및 내부정책을 위반한 경우 이에 따른 조치 절차를 수립∙이행하여야 한다.',
    compliance_cycle: '연간'
  },
  {
    req_id: '2.3.4',
    category: '물리 보안',
    subject: '외부자 계약 변경 및 만료 시 보안',
    detail: '외부자 계약만료, 업무종료, 담당자 변경 시에는 제공한 정보자산 반납, 정보시스템 접근계정 삭제, 중요정보 파기, 업무 수행 중 취득정보의 비밀유지 확약서 징구 등의 보호대책을 이행하여야 한다.',
    compliance_cycle: '분기'
  },
  {
    req_id: '2.4.5',
    category: '물리 보안',
    subject: '보호구역 내 작업',
    detail: '보호구역 내에서의 비인가행위 및 권한 오∙남용 등을 방지하기 위한 작업 절차를 수립∙이행하고, 작업 기록을 주기적으로 검토하여야 한다.',
    compliance_cycle: '분기'
  },
  {
    req_id: '2.4.6',
    category: '물리 보안',
    subject: '반출입 기기 통제',
    detail: '보호구역 내 정보시스템, 모바일 기기, 저장매체 등에 대한 반출입 통제절차를 수립∙이행하고 주기적으로 검토하여야 한다.',
    compliance_cycle: '분기'
  },
  {
    req_id: '2.4.7',
    category: '인증 및 권한관리',
    subject: '업무환경 보안',
    detail: '공용으로 사용하는 사무용 기기(문서고, 공용 PC, 복합기, 파일서버 등) 및 개인 업무환경(업무용 PC, 책상 등)을 통해 개인정보 및 중요정보가 비인가자에게 노출 또는 유출되지 않도록 클린데스크, 정기점검 등 업무환경 보호대책을 수립∙이행하여야 한다.',
    compliance_cycle: '분기'
  },
  {
    req_id: '2.5.5',
    category: '인증 및 권한관리',
    subject: '특수 계정 및 권한 관리',
    detail: '정보시스템 관리, 개인정보 및 중요정보 관리 등 특수 목적을 위하여 사용하는 계정 및 권한은 최소한으로 부여하고 별도로 식별하여 통제하여야 한다.',
    compliance_cycle: '반기'
  },
  {
    req_id: '2.5.6',
    category: '접근통제',
    subject: '접근권한 검토',
    detail: '정보시스템과 개인정보 및 중요정보에 접근하는 사용자 계정의 등록∙이용∙삭제 및 접근권한의 부여∙변경∙삭제 이력을 남기고 주기적으로 검토하여 적정성 여부를 점검하여야 한다.',
    compliance_cycle: '반기'
  },
  {
    req_id: '2.6.2',
    category: '접근통제',
    subject: '정보시스템 접근',
    detail: '서버, 네트워크시스템 등 정보시스템에 접근을 허용하는 사용자, 접근제한 방식, 안전한 접근수단 등을 정의하여 통제하여야 한다.',
    compliance_cycle: '반기'
  },
  {
    req_id: '2.6.3',
    category: '접근통제',
    subject: '응용프로그램 접근',
    detail: '사용자별 업무 및 접근 정보의 중요도 등에 따라 응용프로그램 접근권한을 제한하고, 불필요한 정보 또는 중요정보 노출을 최소화할 수 있도록 기준을 수립하여 적용하여야 한다.',
    compliance_cycle: '반기'
  },
  {
    req_id: '2.6.4',
    category: '접근통제',
    subject: '데이터베이스 접근',
    detail: '테이블 목록 등 데이터베이스 내에서 저장∙관리되고 있는 정보를 식별하고, 정보의 중요도와 응용프로그램 및 사용자 유형 등에 따른 접근통제 정책을 수립∙이행하여야 한다.',
    compliance_cycle: '반기'
  },
  {
    req_id: '2.6.5',
    category: '접근통제',
    subject: '무선 네트워크 접근',
    detail: '무선 네트워크를 사용하는 경우 사용자 인증, 송수신 데이터 암호화, AP 통제 등 무선 네트워크 보호대책을 적용하여야 한다. 또한 AD Hoc 접속, 비인가 AP 사용 등 비인가 무선 네트워크 접속으로부터 보호대책을 수립∙이행하여야 한다.',
    compliance_cycle: '반기'
  },
  {
    req_id: '2.6.6',
    category: '접근통제',
    subject: '원격접근 통제',
    detail: '보호구역 이외 장소에서의 정보시스템 관리 및 개인정보 처리는 원칙적으로 금지하고, 재택근무∙장애대응∙원격협업 등 불가피한 사유로 원격접근을 허용하는 경우 책임자 승인, 접근 단말 지정, 접근 허용범위 및 기간 설정, 강화된 인증, 구간 암호화, 접속단말 보안(백신, 패치 등) 등 보호대책을 수립∙이행하여야 한다.',
    compliance_cycle: '반기'
  },
  {
    req_id: '2.6.7',
    category: '암호화 적용',
    subject: '인터넷 접속 통제',
    detail: '인터넷을 통한 정보 유출, 악성코드 감염, 내부망 침투 등을 예방하기 위하여 주요 정보시스템, 주요 직무 수행 및 개인정보 취급 단말기 등에 대한 인터넷 접속 또는 서비스(P2P, 웹하드, 메신저 등)를 제한하는 등 인터넷 접속 통제 정책을 수립∙이행하여야 한다.',
    compliance_cycle: '반기'
  },
  {
    req_id: '2.8.6',
    category: '시스템 및 서비스 운영관리',
    subject: '운영환경 이관',
    detail: '신규 도입∙개발 또는 변경된 시스템을 운영환경으로 이관할 때는 통제된 절차를 따라야 하고, 실행코드는 시험 및 사용자 인수 절차에 따라 실행되어야 한다.',
    compliance_cycle: '분기'
  },
  {
    req_id: '2.9.6',
    category: '시스템 및 서비스 운영관리',
    subject: '시간 동기화',
    detail: '로그 및 접속기록의 정확성을 보장하고 신뢰성 있는 로그분석을 위하여 관련 정보시스템의 시각을 표준시각으로 동기화하고 주기적으로 관리하여야 한다.',
    compliance_cycle: '연간'
  },
  {
    req_id: '2.10.1',
    category: '시스템 및 서비스 보안관리',
    subject: '보안시스템 운영',
    detail: '보안시스템 유형별로 관리자 지정, 최신 정책 업데이트, 룰셋 변경, 이벤트 모니터링 등의 운영절차를 수립∙이행하고 보안시스템별 정책적용 현황을 관리하여야 한다.',
    compliance_cycle: '연간'
  },
  {
    req_id: '2.10.2',
    category: '시스템 및 서비스 보안관리',
    subject: '클라우드 보안',
    detail: '클라우드 서비스 이용 시 서비스 유형(SaaS, PaaS, IaaS 등)에 따른 비인가 접근, 설정 오류 등에 따라 중요정보와 개인정보가 유∙노출되지 않도록 관리자 접근 및 보안 설정 등에 대한 보호대책을 수립∙이행하여야 한다.',
    compliance_cycle: '연간'
  },
  {
    req_id: '2.10.3',
    category: '시스템 및 서비스 보안관리',
    subject: '공개서버 보안',
    detail: '외부 네트워크에 공개되는 서버의 경우 내부 네트워크와 분리하고 취약점 점검, 접근통제, 인증, 정보 수집∙저장∙공개 절차 등 강화된 보호대책을 수립∙이행하여야 한다.',
    compliance_cycle: '연간'
  },
  {
    req_id: '2.10.4',
    category: '시스템 및 서비스 보안관리',
    subject: '전자거래 및 핀테크 보안',
    detail: '전자거래 및 핀테크 서비스 제공 시 정보유출이나 데이터 조작∙사기 등의 침해사고 예방을 위해 인증∙암호화 등의 보호대책을 수립하고, 결제시스템 등 외부 시스템과 연계할 경우 안전성을 점검하여야 한다.',
    compliance_cycle: '연간'
  },
  {
    req_id: '2.10.5',
    category: '시스템 및 서비스 보안관리',
    subject: '정보전송 보안',
    detail: '타 조직에 개인정보 및 중요정보를 전송할 경우 안전한 전송 정책을 수립하고 조직 간 합의를 통해 관리 책임, 전송방법, 개인정보 및 중요정보 보호를 위한 기술적 보호조치 등을 협약하고 이행하여야 한다.',
    compliance_cycle: '연간'
  },
  {
    req_id: '2.10.6',
    category: '시스템 및 서비스 보안관리',
    subject: '업무용 단말기기 보안',
    detail: 'PC, 모바일 기기 등 단말기기를 업무 목적으로 네트워크에 연결할 경우 기기 인증 및 승인, 접근 범위, 기기 보안설정 등의 접근통제 대책을 수립하고 주기적으로 점검하여야 한다.',
    compliance_cycle: '연간'
  },
  {
    req_id: '2.10.7',
    category: '시스템 및 서비스 보안관리',
    subject: '보조저장매체 관리',
    detail: '보조저장매체를 통하여 개인정보 또는 중요정보의 유출이 발생하거나 악성코드가 감염되지 않도록 관리 절차를 수립∙이행하고, 개인정보 또는 중요정보가 포함된 보조저장매체는 안전한 장소에 보관하여야 한다.',
    compliance_cycle: '연간'
  },
  {
    req_id: '2.10.8',
    category: '시스템 및 서비스 보안관리',
    subject: '패치관리',
    detail: '소프트웨어, 운영체제, 보안시스템 등의 취약점으로 인한 침해사고를 예방하기 위하여 최신 패치를 적용하여야 한다. 다만 서비스 영향을 검토하여 최신 패치 적용이 어려울 경우 별도의 보완대책을 마련하여 이행하여야 한다.',
    compliance_cycle: '연간'
  },
  {
    req_id: '2.10.9',
    category: '사고 예방 및 대응',
    subject: '악성코드 통제',
    detail: '바이러스∙웜∙트로이목마∙랜섬웨어 등의 악성코드로부터 개인정보 및 중요정보, 정보시스템 및 업무용 단말기 등을 보호하기 위하여 악성코드 예방∙탐지∙대응 등의 보호대책을 수립∙이행하여야 한다.',
    compliance_cycle: '연간'
  },
  {
    req_id: '2.11.5',
    category: '재해복구',
    subject: '사고 대응 및 복구',
    detail: '침해사고 및 개인정보 유출 징후나 발생을 인지한 때에는 법적 통지 및 신고 의무를 준수하여야 하며, 절차에 따라 신속하게 대응 및 복구하고 사고분석 후 재발방지 대책을 수립하여 대응체계에 반영하여야 한다.',
    compliance_cycle: '연간'
  },
  {
    req_id: '3.1.1',
    category: '개인정보 수집 시 보호조치',
    subject: '개인정보 수집∙이용',
    detail: '개인정보는 적법하고 정당하게 수집∙이용하여야 하며, 정보주체의 동의를 근거로 수집하는 경우에는 적법한 방법으로 정보주체의 동의를 받아야 한다. 또한 만 14세 미만 아동의 개인정보를 수집하는 경우에는 그 법정대리인의 동의를 받아야 하며 법정대리인이 동의하였는지를 확인하여야 한다.',
    compliance_cycle: '연간'
  },
  {
    req_id: '3.1.2',
    category: '개인정보 수집 시 보호조치',
    subject: '개인정보 수집 제한',
    detail: '개인정보를 수집하는 경우 처리 목적에 필요한 최소한의 개인정보만을 수집하여야 하며, 정보주체가 선택적으로 동의할 수 있는 사항 등에 동의하지 아니한다는 이유로 정보주체에게 재화 또는 서비스의 제공을 거부하지 않아야 한다.',
    compliance_cycle: '연간'
  },
  {
    req_id: '3.1.3',
    category: '개인정보 수집 시 보호조치',
    subject: '주민등록번호 처리 제한',
    detail: '주민등록번호는 법적 근거가 있는 경우를 제외하고는 수집∙이용 등 처리할 수 없으며, 주민등록번호의 처리가 허용된 경우라 하더라도 인터넷 홈페이지 등에서 대체수단을 제공하여야 한다.',
    compliance_cycle: '연간'
  },
  {
    req_id: '3.1.4',
    category: '개인정보 수집 시 보호조치',
    subject: '민감정보 및 고유식별정보의 처리 제한',
    detail: '민감정보와 고유식별정보(주민등록번호 제외)를 처리하기 위해서는 법령에서 구체적으로 처리를 요구하거나 허용하는 경우를 제외하고는 정보주체의 별도 동의를 받아야 한다.',
    compliance_cycle: '연간'
  },
  {
    req_id: '3.1.5',
    category: '개인정보 수집 시 보호조치',
    subject: '개인정보 간접수집',
    detail: '정보주체 이외로부터 개인정보를 수집하거나 제3자로부터 제공받는 경우에는 업무에 필요한 최소한의 개인정보를 수집하거나 제공받아야 하며, 법령에 근거하거나 정보주체의 요구가 있으면 개인정보의 수집 출처, 처리목적, 처리정지의 요구권리를 알려야 한다.',
    compliance_cycle: '연간'
  },
  {
    req_id: '3.1.6',
    category: '개인정보 수집 시 보호조치',
    subject: '영상정보처리기기 설치∙운영',
    detail: '고정형 영상정보처리기기를 공개된 장소에 설치∙운영하거나 이동형 영상정보처리기기를 공개된 장소에서 업무를 목적으로 운영하는 경우 설치 목적 및 위치에 따라 법적 요구사항을 준수하고, 적절한 보호대책을 수립∙이행하여야 한다.',
    compliance_cycle: '연간'
  },
  {
    req_id: '3.1.7',
    category: '개인정보 보유 및 이용 시 보호조치',
    subject: '마케팅 목적의 개인정보 수집∙이용',
    detail: '재화나 서비스의 홍보, 판매 권유, 광고성 정보전송 등 마케팅 목적으로 개인정보를 수집∙이용하는 경우 그 목적을 정보주체가 명확하게 인지할 수 있도록 고지하고 동의를 받아야 한다.',
    compliance_cycle: '연간'
  },
  {
    req_id: '3.2.1',
    category: '개인정보 보유 및 이용 시 보호조치',
    subject: '개인정보 현황관리',
    detail: '수집∙보유하는 개인정보의 항목, 보유량, 처리 목적 및 방법, 보유기간 등 현황을 정기적으로 관리하여야 하며, 공공기관의 경우 이를 법률에서 정한 관계기관의 장에게 등록하여야 한다.',
    compliance_cycle: '연간'
  },
  {
    req_id: '3.2.2',
    category: '개인정보 보유 및 이용 시 보호조치',
    subject: '개인정보 품질보장',
    detail: '수집된 개인정보는 처리 목적에 필요한 범위에서 개인정보의 정확성∙완전성∙최신성이 보장되도록 정보주체에게 관리절차를 제공하여야 한다.',
    compliance_cycle: '연간'
  },
  {
    req_id: '3.2.3',
    category: '개인정보 보유 및 이용 시 보호조치',
    subject: '이용자 단말기 접근 보호',
    detail: '정보주체(이용자)의 이동통신단말장치 내에 저장되어 있는 정보 및 이동통신단말장치에 설치된 기능에 접근이 필요한 경우 이를 명확하게 인지할 수 있도록 알리고 정보주체(이용자)의 동의를 받아야 한다.',
    compliance_cycle: '연간'
  },
  {
    req_id: '3.2.4',
    category: '개인정보 보유 및 이용 시 보호조치',
    subject: '개인정보 목적 외 이용 및 제공',
    detail: '개인정보는 수집 시의 정보주체에게 고지∙동의를 받은 목적 또는 법령에 근거한 범위 내에서만 이용 또는 제공하여야 하며, 이를 초과하여 이용∙제공하려는 때에는 정보주체의 추가 동의를 받거나 관계 법령에 따른 적법한 경우인지 확인하고 적절한 보호대책을 수립∙이행하여야 한다.',
    compliance_cycle: '연간'
  },
  {
    req_id: '3.2.5',
    category: '개인정보 제공 시 보호조치',
    subject: '가명정보 처리',
    detail: '가명정보를 처리하는 경우 목적제한, 결합제한, 안전조치, 금지의무 등 법적 요건을 준수하고 적정 수준의 가명처리를 보장할 수 있도록 가명처리 절차를 수립∙이행하여야 한다.',
    compliance_cycle: '연간'
  },
  {
    req_id: '3.3.2',
    category: '개인정보 제공 시 보호조치',
    subject: '개인정보 처리 업무 위탁',
    detail: '개인정보 처리업무를 제3자에게 위탁하는 경우 위탁하는 업무의 내용과 수탁자 등 관련사항을 공개하여야 한다. 또한 재화 또는 서비스를 홍보하거나 판매를 권유하는 업무를 위탁하는 경우 위탁하는 업무의 내용과 수탁자를 정보주체에게 알려야 한다.',
    compliance_cycle: '연간'
  },
  {
    req_id: '3.3.3',
    category: '개인정보 제공 시 보호조치',
    subject: '영업의 양도 등에 따른 개인정보 이전',
    detail: '영업의 양도∙합병 등으로 개인정보를 이전하거나 이전받는 경우 정보주체 통지 등 적절한 보호조치를 수립∙이행하여야 한다.',
    compliance_cycle: '연간'
  },
  {
    req_id: '3.3.4',
    category: '개인정보 파기 시 보호조치',
    subject: '개인정보 국외이전',
    detail: '개인정보를 국외로 이전하는 경우 국외 이전에 대한 동의, 관련 사항에 대한 공개 등 적절한 보호조치를 수립∙이행하여야 한다.',
    compliance_cycle: '연간'
  },
  {
    req_id: '3.4.1',
    category: '개인정보 파기 시 보호조치',
    subject: '개인정보 파기',
    detail: '개인정보의 보유기간 및 파기 관련 내부 정책을 수립하고 개인정보의 보유기간 경과, 처리목적 달성 등 파기 시점이 도달한 때에는 파기의 안전성 및 완전성이 보장될 수 있는 방법으로 지체 없이 파기하여야 한다.',
    compliance_cycle: '연간'
  },
  {
    req_id: '3.4.2',
    category: '정보주체 권리보호',
    subject: '처리목적 달성 후 보유 시 조치',
    detail: '개인정보의 보유기간 경과 또는 처리목적 달성 후에도 관련 법령 등에 따라 파기하지 아니하고 보존하는 경우에는 해당 목적에 필요한 최소한의 항목으로 제한하고 다른 개인정보와 분리하여 저장∙관리하여야 한다.',
    compliance_cycle: '연간'
  },
  {
    req_id: '3.5.1',
    category: '정보주체 권리보호',
    subject: '개인정보 처리방침 공개',
    detail: '개인정보의 처리 목적 등 필요한 사항을 모두 포함하여 정보주체가 알기 쉽도록 개인정보 처리방침을 수립하고, 이를 정보주체가 언제든지 쉽게 확인할 수 있도록 적절한 방법에 따라 공개하고 지속적으로 현행화하여야 한다.',
    compliance_cycle: '연간'
  },
  {
    req_id: '3.5.2',
    category: '정보주체 권리보호',
    subject: '정보주체 권리보장',
    detail: '정보주체가 개인정보의 열람, 정정∙삭제, 처리정지, 이의제기, 동의철회 등 요구를 수집 방법∙절차보다 쉽게 할 수 있도록 권리행사 방법 및 절차를 수립∙이행하고, 정보주체의 요구를 받은 경우 지체 없이 처리하고 관련 기록을 남겨야 한다. 또한 정보주체의 사생활 침해, 명예훼손 등 타인의 권리를 침해하는 정보가 유통되지 않도록 삭제 요청, 임시조치 등의 기준',
    compliance_cycle: '연간'
  },
  {
    req_id: '3.5.3',
    category: '정보주체 권리보호',
    subject: '정보주체에 대한 통지',
    detail: '개인정보의 이용∙제공 내역 등 정보주체에게 통지하여야 할 사항을 파악하여 그 내용을 주기적으로 통지하여야 한다.',
    compliance_cycle: '연간'
  },
];

export const soaSummary = {
  reportDate: '2025-01-01',
  reportVersion: 'v1.1',
  totalControls: 170,
  applied: 157,
  partiallyApplied: 13,
  notApplicable: 0,
  ismsGapCount: 60,
  ismsMappedCount: 110,
  domains: [
    { name: '5. 조직 통제', total: 87, applied: 84, partial: 3, na: 0 },
    { name: '7. 물리적 통제', total: 28, applied: 23, partial: 5, na: 0 },
    { name: '8. 기술적 통제', total: 55, applied: 50, partial: 5, na: 0 },
  ]
};